#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ActivityBrowserAttributionsModal

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ActivityBrowserAttributionsModal.ActivityBrowserAttributionsModal_C
// 0x0030 (0x04A8 - 0x0478)
class UActivityBrowserAttributionsModal_C final : public UFortActivityBrowserAttributionsModal
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0478(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_UIKit_Backplate_C*                 Backplate_Attributions;                            // 0x0480(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USafeZone*                              SafeZone_ButtonCloseTouch;                         // 0x0488(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_Title;                                        // 0x0490(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_UIKit_Dialog_Base_C*               WBP_UIKit_Dialog_Base;                             // 0x0498(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USoundBase*                             IntroWhooshSound;                                  // 0x04A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void BP_OnActivated();
	void ExecuteUbergraph_ActivityBrowserAttributionsModal(int32 EntryPoint);
	class FText GetAttributionsTextFormat(const class FText& Title, const class FText& Author, const class FText& License);
	class FText GetCreatorTextFormat(const class FText& CreatorName);
	class FText GetLinkCodeTextFormat(const class FText& LinkCode);
	void OnAttributionsModalInitialized();
	void OnCreditsModalInitialized();
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ActivityBrowserAttributionsModal_C">();
	}
	static class UActivityBrowserAttributionsModal_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UActivityBrowserAttributionsModal_C>();
	}
};
static_assert(alignof(UActivityBrowserAttributionsModal_C) == 0x000008, "Wrong alignment on UActivityBrowserAttributionsModal_C");
static_assert(sizeof(UActivityBrowserAttributionsModal_C) == 0x0004A8, "Wrong size on UActivityBrowserAttributionsModal_C");

}

