#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AlterationWidgetButton

#include "Basic.hpp"

#include "FortniteGame_structs.hpp"
#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AlterationWidgetButton.AlterationWidgetButton_C
// 0x00E0 (0x0978 - 0x0898)
class UAlterationWidgetButton_C final : public UFortAlterationButtonWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0898(0x0008)(Transient, DuplicateTransient)
	class UWidgetAnimation*                       PanelLoad;                                         // 0x08A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       TriangelUpgrade;                                   // 0x08A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UAlterationWidget_C*                    AlterationWidget;                                  // 0x08B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Flash;                                             // 0x08B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Shine;                                             // 0x08C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 TriangleUpgrade;                                   // 0x08C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                          bIncludeName;                                      // 0x08D0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)
	bool                                          bIncludeShortDescription;                          // 0x08D1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)
	bool                                          bIncludeDescription;                               // 0x08D2(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)
	EFortBrushSize                                IconSize;                                          // 0x08D3(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          bUseLargeFormatName;                               // 0x08D4(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)
	uint8                                         Pad_8D5[0x3];                                      // 0x08D5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 Locked_Description_Style;                          // 0x08D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 Locked_Text_Style;                                 // 0x08E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ShouldShowRarity;                                  // 0x08E8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)
	uint8                                         Pad_8E9[0x7];                                      // 0x08E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               Triangles_Upgrade;                                 // 0x08F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FFortRarityItemData                    RarityData;                                        // 0x08F8(0x0080)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteUbergraph_AlterationWidgetButton(int32 EntryPoint);
	void Construct();
	void OnSetup();
	void TriggerModificationAnimation();
	void IntroReset();
	void IntroStart();
	void Update_Colors();
	void Setup_Triangles();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AlterationWidgetButton_C">();
	}
	static class UAlterationWidgetButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAlterationWidgetButton_C>();
	}
};
static_assert(alignof(UAlterationWidgetButton_C) == 0x000008, "Wrong alignment on UAlterationWidgetButton_C");
static_assert(sizeof(UAlterationWidgetButton_C) == 0x000978, "Wrong size on UAlterationWidgetButton_C");
static_assert(offsetof(UAlterationWidgetButton_C, UberGraphFrame) == 0x000898, "Member 'UAlterationWidgetButton_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UAlterationWidgetButton_C, PanelLoad) == 0x0008A0, "Member 'UAlterationWidgetButton_C::PanelLoad' has a wrong offset!");
static_assert(offsetof(UAlterationWidgetButton_C, TriangelUpgrade) == 0x0008A8, "Member 'UAlterationWidgetButton_C::TriangelUpgrade' has a wrong offset!");
static_assert(offsetof(UAlterationWidgetButton_C, AlterationWidget) == 0x0008B0, "Member 'UAlterationWidgetButton_C::AlterationWidget' has a wrong offset!");
static_assert(offsetof(UAlterationWidgetButton_C, Flash) == 0x0008B8, "Member 'UAlterationWidgetButton_C::Flash' has a wrong offset!");
static_assert(offsetof(UAlterationWidgetButton_C, Shine) == 0x0008C0, "Member 'UAlterationWidgetButton_C::Shine' has a wrong offset!");
static_assert(offsetof(UAlterationWidgetButton_C, TriangleUpgrade) == 0x0008C8, "Member 'UAlterationWidgetButton_C::TriangleUpgrade' has a wrong offset!");
static_assert(offsetof(UAlterationWidgetButton_C, bIncludeName) == 0x0008D0, "Member 'UAlterationWidgetButton_C::bIncludeName' has a wrong offset!");
static_assert(offsetof(UAlterationWidgetButton_C, bIncludeShortDescription) == 0x0008D1, "Member 'UAlterationWidgetButton_C::bIncludeShortDescription' has a wrong offset!");
static_assert(offsetof(UAlterationWidgetButton_C, bIncludeDescription) == 0x0008D2, "Member 'UAlterationWidgetButton_C::bIncludeDescription' has a wrong offset!");
static_assert(offsetof(UAlterationWidgetButton_C, IconSize) == 0x0008D3, "Member 'UAlterationWidgetButton_C::IconSize' has a wrong offset!");
static_assert(offsetof(UAlterationWidgetButton_C, bUseLargeFormatName) == 0x0008D4, "Member 'UAlterationWidgetButton_C::bUseLargeFormatName' has a wrong offset!");
static_assert(offsetof(UAlterationWidgetButton_C, Locked_Description_Style) == 0x0008D8, "Member 'UAlterationWidgetButton_C::Locked_Description_Style' has a wrong offset!");
static_assert(offsetof(UAlterationWidgetButton_C, Locked_Text_Style) == 0x0008E0, "Member 'UAlterationWidgetButton_C::Locked_Text_Style' has a wrong offset!");
static_assert(offsetof(UAlterationWidgetButton_C, ShouldShowRarity) == 0x0008E8, "Member 'UAlterationWidgetButton_C::ShouldShowRarity' has a wrong offset!");
static_assert(offsetof(UAlterationWidgetButton_C, Triangles_Upgrade) == 0x0008F0, "Member 'UAlterationWidgetButton_C::Triangles_Upgrade' has a wrong offset!");
static_assert(offsetof(UAlterationWidgetButton_C, RarityData) == 0x0008F8, "Member 'UAlterationWidgetButton_C::RarityData' has a wrong offset!");

}

