#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AnimationBudgetAllocator

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// Class AnimationBudgetAllocator.SkeletalMeshComponentBudgeted
// 0x0028 (0x0BA0 - 0x0B78)
class USkeletalMeshComponentBudgeted : public USkeletalMeshComponent
{
public:
	uint8                                         Pad_B78[0x20];                                     // 0x0B78(0x0020)(Fixing Size After Last Property [ Dumper-7 ])
	uint8                                         bAutoRegisterWithBudgetAllocator : 1;              // 0x0B98(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate))
	uint8                                         bAutoCalculateSignificance : 1;                    // 0x0B98(0x0001)(BitIndex: 0x01, PropSize: 0x0001 (Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate))
	uint8                                         Pad_B99[0x7];                                      // 0x0B99(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void SetAutoRegisterWithBudgetAllocator(bool bInAutoRegisterWithBudgetAllocator);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"SkeletalMeshComponentBudgeted">();
	}
	static class USkeletalMeshComponentBudgeted* GetDefaultObj()
	{
		return GetDefaultObjImpl<USkeletalMeshComponentBudgeted>();
	}
};
static_assert(alignof(USkeletalMeshComponentBudgeted) == 0x000008, "Wrong alignment on USkeletalMeshComponentBudgeted");
static_assert(sizeof(USkeletalMeshComponentBudgeted) == 0x000BA0, "Wrong size on USkeletalMeshComponentBudgeted");

}

