#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AnnualRefundTokenUI

#include "Basic.hpp"

#include "AnnualRefundTokenUI_structs.hpp"


namespace SDK::Params
{

// Function AnnualRefundTokenUI.FortPurchaseHistoryEntryBase.UpdateItemList
// 0x0010 (0x0010 - 0x0000)
struct FortPurchaseHistoryEntryBase_UpdateItemList final
{
public:
	TArray<class UFortCosmeticItemCard*>          ItemCards;                                         // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, ContainsInstancedReference, NativeAccessSpecifierPublic)
};
static_assert(alignof(FortPurchaseHistoryEntryBase_UpdateItemList) == 0x000008, "Wrong alignment on FortPurchaseHistoryEntryBase_UpdateItemList");
static_assert(sizeof(FortPurchaseHistoryEntryBase_UpdateItemList) == 0x000010, "Wrong size on FortPurchaseHistoryEntryBase_UpdateItemList");

// Function AnnualRefundTokenUI.FortPurchaseHistoryEntry.OnSetHistory
// 0x0010 (0x0010 - 0x0000)
struct FortPurchaseHistoryEntry_OnSetHistory final
{
public:
	bool                                          bHasBeenRefunded;                                  // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsCancelPurchaseEligible;                         // 0x0001(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsTokenlessRefund;                                // 0x0002(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bPlayerHasTokens;                                  // 0x0003(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bNonRefundable;                                    // 0x0004(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsPartOfABundle;                                   // 0x0005(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsNextRefundable;                                  // 0x0006(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_7[0x1];                                        // 0x0007(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         IndexInBundle;                                     // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         NumPurchasesInBundle;                              // 0x000C(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FortPurchaseHistoryEntry_OnSetHistory) == 0x000004, "Wrong alignment on FortPurchaseHistoryEntry_OnSetHistory");
static_assert(sizeof(FortPurchaseHistoryEntry_OnSetHistory) == 0x000010, "Wrong size on FortPurchaseHistoryEntry_OnSetHistory");

// Function AnnualRefundTokenUI.FortPurchaseHistoryEntry.SetPurchaseText
// 0x0028 (0x0028 - 0x0000)
struct FortPurchaseHistoryEntry_SetPurchaseText final
{
public:
	class FText                                   PurchaseDateText;                                  // 0x0000(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	class FText                                   RefundDateText;                                    // 0x0010(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	bool                                          bHasBeenRefunded;                                  // 0x0020(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EFortPurchaseHistoryRefundType                RefundType;                                        // 0x0021(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_22[0x6];                                       // 0x0022(0x0006)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FortPurchaseHistoryEntry_SetPurchaseText) == 0x000008, "Wrong alignment on FortPurchaseHistoryEntry_SetPurchaseText");
static_assert(sizeof(FortPurchaseHistoryEntry_SetPurchaseText) == 0x000028, "Wrong size on FortPurchaseHistoryEntry_SetPurchaseText");

// Function AnnualRefundTokenUI.FortPurchaseHistoryEntry.SetupItemCard
// 0x0010 (0x0010 - 0x0000)
struct FortPurchaseHistoryEntry_SetupItemCard final
{
public:
	const class UFortCosmeticItemCard*            ItemCard;                                          // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	const class UFortItem*                        Item;                                              // 0x0008(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FortPurchaseHistoryEntry_SetupItemCard) == 0x000008, "Wrong alignment on FortPurchaseHistoryEntry_SetupItemCard");
static_assert(sizeof(FortPurchaseHistoryEntry_SetupItemCard) == 0x000010, "Wrong size on FortPurchaseHistoryEntry_SetupItemCard");

// Function AnnualRefundTokenUI.FortPurchaseHistoryBundleEntry.SetExpandButtonText
// 0x0004 (0x0004 - 0x0000)
struct FortPurchaseHistoryBundleEntry_SetExpandButtonText final
{
public:
	int32                                         NumPurchases;                                      // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FortPurchaseHistoryBundleEntry_SetExpandButtonText) == 0x000004, "Wrong alignment on FortPurchaseHistoryBundleEntry_SetExpandButtonText");
static_assert(sizeof(FortPurchaseHistoryBundleEntry_SetExpandButtonText) == 0x000004, "Wrong size on FortPurchaseHistoryBundleEntry_SetExpandButtonText");

// Function AnnualRefundTokenUI.FortAnnualRefundTicket.OnUpdateAvailableState
// 0x0001 (0x0001 - 0x0000)
struct FortAnnualRefundTicket_OnUpdateAvailableState final
{
public:
	bool                                          bIsAvailable;                                      // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FortAnnualRefundTicket_OnUpdateAvailableState) == 0x000001, "Wrong alignment on FortAnnualRefundTicket_OnUpdateAvailableState");
static_assert(sizeof(FortAnnualRefundTicket_OnUpdateAvailableState) == 0x000001, "Wrong size on FortAnnualRefundTicket_OnUpdateAvailableState");

// Function AnnualRefundTokenUI.FortAnnualRefundTicket.OnUpdatePendingState
// 0x0001 (0x0001 - 0x0000)
struct FortAnnualRefundTicket_OnUpdatePendingState final
{
public:
	bool                                          bIsPending;                                        // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FortAnnualRefundTicket_OnUpdatePendingState) == 0x000001, "Wrong alignment on FortAnnualRefundTicket_OnUpdatePendingState");
static_assert(sizeof(FortAnnualRefundTicket_OnUpdatePendingState) == 0x000001, "Wrong size on FortAnnualRefundTicket_OnUpdatePendingState");

// Function AnnualRefundTokenUI.FortPurchaseHistoryScreen.BP_IsShowingPurchases
// 0x0001 (0x0001 - 0x0000)
struct FortPurchaseHistoryScreen_BP_IsShowingPurchases final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FortPurchaseHistoryScreen_BP_IsShowingPurchases) == 0x000001, "Wrong alignment on FortPurchaseHistoryScreen_BP_IsShowingPurchases");
static_assert(sizeof(FortPurchaseHistoryScreen_BP_IsShowingPurchases) == 0x000001, "Wrong size on FortPurchaseHistoryScreen_BP_IsShowingPurchases");

// Function AnnualRefundTokenUI.FortRefundConfirmation.BP_UpdateItemsList
// 0x0018 (0x0018 - 0x0000)
struct FortRefundConfirmation_BP_UpdateItemsList final
{
public:
	TArray<class UFortItemDefinition*>            SelectedItemDefs;                                  // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
	int32                                         TotalMtxPaid;                                      // 0x0010(0x0004)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FortRefundConfirmation_BP_UpdateItemsList) == 0x000008, "Wrong alignment on FortRefundConfirmation_BP_UpdateItemsList");
static_assert(sizeof(FortRefundConfirmation_BP_UpdateItemsList) == 0x000018, "Wrong size on FortRefundConfirmation_BP_UpdateItemsList");

// Function AnnualRefundTokenUI.FortRefundConfirmation.BP_UpdateRefundType
// 0x0002 (0x0002 - 0x0000)
struct FortRefundConfirmation_BP_UpdateRefundType final
{
public:
	EFortPurchaseHistoryRefundType                RefundType;                                        // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bBundledRefund;                                    // 0x0001(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FortRefundConfirmation_BP_UpdateRefundType) == 0x000001, "Wrong alignment on FortRefundConfirmation_BP_UpdateRefundType");
static_assert(sizeof(FortRefundConfirmation_BP_UpdateRefundType) == 0x000002, "Wrong size on FortRefundConfirmation_BP_UpdateRefundType");

}

