#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Prj_Ranged_Rocket_Military_Athena

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function B_Prj_Ranged_Rocket_Military_Athena.B_Prj_Ranged_Rocket_Military_Athena_C.ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena
// 0x04B0 (0x04B0 - 0x0000)
struct B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue;          // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_MakeRotator_ReturnValue;                  // 0x0008(0x000C)(IsPlainOldData, NoDestructor)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             CallFunc_K2_AddLocalRotation_SweepHitResult;       // 0x0018(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FHitResult                             CallFunc_K2_AddLocalRotation_SweepHitResult1;      // 0x00A0(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	float                                         CallFunc_RandomFloatInRange_ReturnValue;           // 0x0128(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_MakeRotator_ReturnValue1;                 // 0x012C(0x000C)(IsPlainOldData, NoDestructor)
	struct FHitResult                             CallFunc_K2_AddLocalRotation_SweepHitResult2;      // 0x0138(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_IsBeingKilled_ReturnValue;                // 0x01C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsActive_ReturnValue;                     // 0x01C1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x01C2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1C3[0x5];                                      // 0x01C3(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerCameraManager*                   CallFunc_GetPlayerCameraManager_ReturnValue;       // 0x01C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x01D0(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Subtract_VectorVector_ReturnValue;        // 0x01DC(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_VSize_ReturnValue;                        // 0x01E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue;         // 0x01EC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1ED[0x3];                                      // 0x01ED(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           CallFunc_K2_SetTimer_ReturnValue;                  // 0x01F0(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue1;     // 0x01F8(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_204[0x4];                                      // 0x0204(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         K2Node_Event_HitActors;                            // 0x0208(0x0010)(ConstParm, ZeroConstructor, ReferenceParm)
	TArray<struct FHitResult>                     K2Node_Event_HitResults;                           // 0x0218(0x0010)(ConstParm, ZeroConstructor, ReferenceParm, ContainsInstancedReference)
	struct FHitResult                             K2Node_Event_Hit1;                                 // 0x0228(0x0088)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_BreakHitResult_bBlockingHit;              // 0x02B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap;           // 0x02B1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2B2[0x2];                                      // 0x02B2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakHitResult_Time;                      // 0x02B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance;                  // 0x02B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Location;                  // 0x02BC(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint;               // 0x02C8(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal;                    // 0x02D4(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal;              // 0x02E0(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2EC[0x4];                                      // 0x02EC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat;                   // 0x02F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor;                  // 0x02F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent;              // 0x0300(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName;               // 0x0308(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem;                   // 0x0310(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex;                 // 0x0314(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceStart;                // 0x0318(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd;                  // 0x0324(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_K2_GetComponentRotation_ReturnValue;      // 0x0330(0x000C)(IsPlainOldData, NoDestructor)
	struct FRotator                               CallFunc_MakeRotFromX_ReturnValue;                 // 0x033C(0x000C)(IsPlainOldData, NoDestructor)
	struct FRotator                               CallFunc_MakeRotFromZ_ReturnValue;                 // 0x0348(0x000C)(IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_Multiply_VectorFloat_ReturnValue;         // 0x0354(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x0360(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue2;     // 0x036C(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaSeconds;                         // 0x0378(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_37C[0x4];                                      // 0x037C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             CallFunc_K2_SetWorldLocation_SweepHitResult;       // 0x0380(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	class UParticleSystemComponent*               CallFunc_SpawnEmitterAtLocation_ReturnValue;       // 0x0408(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             K2Node_Event_Hit;                                  // 0x0410(0x0088)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_IsDedicatedServer_ReturnValue;            // 0x0498(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsDedicatedServer_ReturnValue1;           // 0x0499(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_49A[0x6];                                      // 0x049A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UParticleSystemComponent*               CallFunc_SpawnEmitterAtLocation_ReturnValue1;      // 0x04A0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               CallFunc_SpawnEmitterAtLocation_ReturnValue2;      // 0x04A8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena) == 0x000008, "Wrong alignment on B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena");
static_assert(sizeof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena) == 0x0004B0, "Wrong size on B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, EntryPoint) == 0x000000, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::EntryPoint' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_Multiply_FloatFloat_ReturnValue) == 0x000004, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_Multiply_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_MakeRotator_ReturnValue) == 0x000008, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_MakeRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_K2_AddLocalRotation_SweepHitResult) == 0x000018, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_K2_AddLocalRotation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_K2_AddLocalRotation_SweepHitResult1) == 0x0000A0, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_K2_AddLocalRotation_SweepHitResult1' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_RandomFloatInRange_ReturnValue) == 0x000128, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_RandomFloatInRange_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_MakeRotator_ReturnValue1) == 0x00012C, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_MakeRotator_ReturnValue1' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_K2_AddLocalRotation_SweepHitResult2) == 0x000138, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_K2_AddLocalRotation_SweepHitResult2' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_IsBeingKilled_ReturnValue) == 0x0001C0, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_IsBeingKilled_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_IsActive_ReturnValue) == 0x0001C1, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_IsActive_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, K2Node_SwitchEnum_CmpSuccess) == 0x0001C2, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_GetPlayerCameraManager_ReturnValue) == 0x0001C8, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_GetPlayerCameraManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x0001D0, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_Subtract_VectorVector_ReturnValue) == 0x0001DC, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_Subtract_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_VSize_ReturnValue) == 0x0001E8, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_VSize_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_LessEqual_FloatFloat_ReturnValue) == 0x0001EC, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_LessEqual_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_K2_SetTimer_ReturnValue) == 0x0001F0, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_K2_SetTimer_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_K2_GetComponentLocation_ReturnValue1) == 0x0001F8, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_K2_GetComponentLocation_ReturnValue1' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, K2Node_Event_HitActors) == 0x000208, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::K2Node_Event_HitActors' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, K2Node_Event_HitResults) == 0x000218, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::K2Node_Event_HitResults' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, K2Node_Event_Hit1) == 0x000228, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::K2Node_Event_Hit1' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_BreakHitResult_bBlockingHit) == 0x0002B0, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_BreakHitResult_bBlockingHit' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_BreakHitResult_bInitialOverlap) == 0x0002B1, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_BreakHitResult_bInitialOverlap' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_BreakHitResult_Time) == 0x0002B4, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_BreakHitResult_Time' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_BreakHitResult_Distance) == 0x0002B8, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_BreakHitResult_Distance' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_BreakHitResult_Location) == 0x0002BC, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_BreakHitResult_Location' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_BreakHitResult_ImpactPoint) == 0x0002C8, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_BreakHitResult_ImpactPoint' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_BreakHitResult_Normal) == 0x0002D4, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_BreakHitResult_Normal' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_BreakHitResult_ImpactNormal) == 0x0002E0, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_BreakHitResult_ImpactNormal' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_BreakHitResult_PhysMat) == 0x0002F0, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_BreakHitResult_PhysMat' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_BreakHitResult_HitActor) == 0x0002F8, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_BreakHitResult_HitActor' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_BreakHitResult_HitComponent) == 0x000300, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_BreakHitResult_HitComponent' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_BreakHitResult_HitBoneName) == 0x000308, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_BreakHitResult_HitBoneName' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_BreakHitResult_HitItem) == 0x000310, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_BreakHitResult_HitItem' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_BreakHitResult_FaceIndex) == 0x000314, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_BreakHitResult_FaceIndex' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_BreakHitResult_TraceStart) == 0x000318, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_BreakHitResult_TraceStart' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_BreakHitResult_TraceEnd) == 0x000324, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_BreakHitResult_TraceEnd' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_K2_GetComponentRotation_ReturnValue) == 0x000330, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_K2_GetComponentRotation_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_MakeRotFromX_ReturnValue) == 0x00033C, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_MakeRotFromX_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_MakeRotFromZ_ReturnValue) == 0x000348, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_MakeRotFromZ_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_Multiply_VectorFloat_ReturnValue) == 0x000354, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_Multiply_VectorFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_Add_VectorVector_ReturnValue) == 0x000360, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_K2_GetComponentLocation_ReturnValue2) == 0x00036C, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_K2_GetComponentLocation_ReturnValue2' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, K2Node_Event_DeltaSeconds) == 0x000378, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::K2Node_Event_DeltaSeconds' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_K2_SetWorldLocation_SweepHitResult) == 0x000380, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_K2_SetWorldLocation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_SpawnEmitterAtLocation_ReturnValue) == 0x000408, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_SpawnEmitterAtLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, K2Node_Event_Hit) == 0x000410, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::K2Node_Event_Hit' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_IsDedicatedServer_ReturnValue) == 0x000498, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_IsDedicatedServer_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_IsDedicatedServer_ReturnValue1) == 0x000499, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_IsDedicatedServer_ReturnValue1' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_SpawnEmitterAtLocation_ReturnValue1) == 0x0004A0, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_SpawnEmitterAtLocation_ReturnValue1' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena, CallFunc_SpawnEmitterAtLocation_ReturnValue2) == 0x0004A8, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ExecuteUbergraph_B_Prj_Ranged_Rocket_Military_Athena::CallFunc_SpawnEmitterAtLocation_ReturnValue2' has a wrong offset!");

// Function B_Prj_Ranged_Rocket_Military_Athena.B_Prj_Ranged_Rocket_Military_Athena_C.OnBounce
// 0x0088 (0x0088 - 0x0000)
struct B_Prj_Ranged_Rocket_Military_Athena_C_OnBounce final
{
public:
	struct FHitResult                             Hit;                                               // 0x0000(0x0088)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(B_Prj_Ranged_Rocket_Military_Athena_C_OnBounce) == 0x000008, "Wrong alignment on B_Prj_Ranged_Rocket_Military_Athena_C_OnBounce");
static_assert(sizeof(B_Prj_Ranged_Rocket_Military_Athena_C_OnBounce) == 0x000088, "Wrong size on B_Prj_Ranged_Rocket_Military_Athena_C_OnBounce");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_OnBounce, Hit) == 0x000000, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_OnBounce::Hit' has a wrong offset!");

// Function B_Prj_Ranged_Rocket_Military_Athena.B_Prj_Ranged_Rocket_Military_Athena_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct B_Prj_Ranged_Rocket_Military_Athena_C_ReceiveTick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(B_Prj_Ranged_Rocket_Military_Athena_C_ReceiveTick) == 0x000004, "Wrong alignment on B_Prj_Ranged_Rocket_Military_Athena_C_ReceiveTick");
static_assert(sizeof(B_Prj_Ranged_Rocket_Military_Athena_C_ReceiveTick) == 0x000004, "Wrong size on B_Prj_Ranged_Rocket_Military_Athena_C_ReceiveTick");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_ReceiveTick, DeltaSeconds) == 0x000000, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_ReceiveTick::DeltaSeconds' has a wrong offset!");

// Function B_Prj_Ranged_Rocket_Military_Athena.B_Prj_Ranged_Rocket_Military_Athena_C.OnStop
// 0x0088 (0x0088 - 0x0000)
struct B_Prj_Ranged_Rocket_Military_Athena_C_OnStop final
{
public:
	struct FHitResult                             Hit;                                               // 0x0000(0x0088)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(B_Prj_Ranged_Rocket_Military_Athena_C_OnStop) == 0x000008, "Wrong alignment on B_Prj_Ranged_Rocket_Military_Athena_C_OnStop");
static_assert(sizeof(B_Prj_Ranged_Rocket_Military_Athena_C_OnStop) == 0x000088, "Wrong size on B_Prj_Ranged_Rocket_Military_Athena_C_OnStop");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_OnStop, Hit) == 0x000000, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_OnStop::Hit' has a wrong offset!");

// Function B_Prj_Ranged_Rocket_Military_Athena.B_Prj_Ranged_Rocket_Military_Athena_C.OnExploded
// 0x0020 (0x0020 - 0x0000)
struct B_Prj_Ranged_Rocket_Military_Athena_C_OnExploded final
{
public:
	TArray<class AActor*>                         HitActors;                                         // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm)
	TArray<struct FHitResult>                     HitResults;                                        // 0x0010(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(B_Prj_Ranged_Rocket_Military_Athena_C_OnExploded) == 0x000008, "Wrong alignment on B_Prj_Ranged_Rocket_Military_Athena_C_OnExploded");
static_assert(sizeof(B_Prj_Ranged_Rocket_Military_Athena_C_OnExploded) == 0x000020, "Wrong size on B_Prj_Ranged_Rocket_Military_Athena_C_OnExploded");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_OnExploded, HitActors) == 0x000000, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_OnExploded::HitActors' has a wrong offset!");
static_assert(offsetof(B_Prj_Ranged_Rocket_Military_Athena_C_OnExploded, HitResults) == 0x000010, "Member 'B_Prj_Ranged_Rocket_Military_Athena_C_OnExploded::HitResults' has a wrong offset!");

}

