#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Prj_Ranged_Rocket

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_Prj_Ranged_Rocket.B_Prj_Ranged_Rocket_C
// 0x0138 (0x0800 - 0x06C8)
class AB_Prj_Ranged_Rocket_C : public AFortProjectileBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x06C8(0x0008)(Transient, DuplicateTransient)
	class UPostProcessComponent*                  PP_Explode;                                        // 0x06D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        Rocket_AudioComponent;                             // 0x06D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Mesh;                                              // 0x06E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         PPFader_PPFade_7424DD024FE8AE2B8B68448F1966ED3C;   // 0x06E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            PPFader__Direction_7424DD024FE8AE2B8B68448F1966ED3C; // 0x06EC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6ED[0x3];                                      // 0x06ED(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     PPFader;                                           // 0x06F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               Ribbon_Trail_PSC;                                  // 0x06F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               Water_Explosion_PSC;                               // 0x0700(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystem*                        Ribbon_Trail_PS;                                   // 0x0708(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystem*                        Water_Explosion_PS;                                // 0x0710(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystem*                        Explosion_Generic_PS;                              // 0x0718(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               Explosion_Generic_PSC;                             // 0x0720(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             Rocket_Projectile_Explosion_Sound;                 // 0x0728(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                StopLocation;                                      // 0x0730(0x000C)(Edit, BlueprintVisible, Net, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_73C[0x4];                                      // 0x073C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<EObjectTypeQuery>                      ObjectsToTraceAgainst;                             // 0x0740(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance)
	class UParticleSystem*                        Explosion_Flesh_Damage_PS;                         // 0x0750(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               StopRotZ;                                          // 0x0758(0x000C)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	float                                         TrailLifetime;                                     // 0x0764(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               Explosion_Flesh_Damage_PSC;                        // 0x0768(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             Rocket_Projectile_Explosion_Water_Sound;           // 0x0770(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             Rocket_Projectile_InAir_Sound;                     // 0x0778(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               RocketTrailPS;                                     // 0x0780(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Tick_Delta;                                        // 0x0788(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         RocketSpinRate;                                    // 0x078C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Explosion_Impact_Offset;                           // 0x0790(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               RocketSpin;                                        // 0x0794(0x000C)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	struct FVector                                RocketScale;                                       // 0x07A0(0x000C)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          TimerMaxReached_;                                  // 0x07AC(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7AD[0x3];                                      // 0x07AD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInterface*                     Ground_Decal;                                      // 0x07B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               Ground_Decal_MID;                                  // 0x07B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Decal_Size_Max;                                    // 0x07C0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Decal_Size_Min;                                    // 0x07C4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                DecalLocation;                                     // 0x07C8(0x000C)(Edit, BlueprintVisible, Net, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7D4[0x4];                                      // 0x07D4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UParticleSystem*                        Rocket_Trail_Template;                             // 0x07D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EPhysicalSurface                              SurfaceType;                                       // 0x07E0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7E1[0x7];                                      // 0x07E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UParticleSystemComponent*               Explosion_PS;                                      // 0x07E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UForceFeedbackEffect*                   ExplosionForceFeedbackNear;                        // 0x07F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UForceFeedbackEffect*                   ExplosionForceFeedbackFar;                         // 0x07F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_B_Prj_Ranged_Rocket(int32 EntryPoint);
	void ParticleCollide(class FName EventName, float EmitterTime, int32 ParticleTime, const struct FVector& Location, const struct FVector& Velocity, const struct FVector& Direction, const struct FVector& Normal, class FName BoneName, class UPhysicalMaterial* PhysMat);
	void ReceiveDestroyed();
	void ReceiveTick(float DeltaSeconds);
	void OnExploded(const TArray<class AActor*>& HitActors, const TArray<struct FHitResult>& HitResults);
	void FuseTimerMax();
	void ReceiveBeginPlay();
	void OnStop(const struct FHitResult& Hit);
	void OnBounce(const struct FHitResult& Hit);
	void PPFader__UpdateFunc();
	void PPFader__FinishedFunc();
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_Prj_Ranged_Rocket_C">();
	}
	static class AB_Prj_Ranged_Rocket_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_Prj_Ranged_Rocket_C>();
	}
};
static_assert(alignof(AB_Prj_Ranged_Rocket_C) == 0x000008, "Wrong alignment on AB_Prj_Ranged_Rocket_C");
static_assert(sizeof(AB_Prj_Ranged_Rocket_C) == 0x000800, "Wrong size on AB_Prj_Ranged_Rocket_C");
static_assert(offsetof(AB_Prj_Ranged_Rocket_C, UberGraphFrame) == 0x0006C8, "Member 'AB_Prj_Ranged_Rocket_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_Rocket_C, PP_Explode) == 0x0006D0, "Member 'AB_Prj_Ranged_Rocket_C::PP_Explode' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_Rocket_C, Rocket_AudioComponent) == 0x0006D8, "Member 'AB_Prj_Ranged_Rocket_C::Rocket_AudioComponent' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_Rocket_C, Mesh) == 0x0006E0, "Member 'AB_Prj_Ranged_Rocket_C::Mesh' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_Rocket_C, PPFader_PPFade_7424DD024FE8AE2B8B68448F1966ED3C) == 0x0006E8, "Member 'AB_Prj_Ranged_Rocket_C::PPFader_PPFade_7424DD024FE8AE2B8B68448F1966ED3C' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_Rocket_C, PPFader__Direction_7424DD024FE8AE2B8B68448F1966ED3C) == 0x0006EC, "Member 'AB_Prj_Ranged_Rocket_C::PPFader__Direction_7424DD024FE8AE2B8B68448F1966ED3C' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_Rocket_C, PPFader) == 0x0006F0, "Member 'AB_Prj_Ranged_Rocket_C::PPFader' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_Rocket_C, Ribbon_Trail_PSC) == 0x0006F8, "Member 'AB_Prj_Ranged_Rocket_C::Ribbon_Trail_PSC' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_Rocket_C, Water_Explosion_PSC) == 0x000700, "Member 'AB_Prj_Ranged_Rocket_C::Water_Explosion_PSC' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_Rocket_C, Ribbon_Trail_PS) == 0x000708, "Member 'AB_Prj_Ranged_Rocket_C::Ribbon_Trail_PS' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_Rocket_C, Water_Explosion_PS) == 0x000710, "Member 'AB_Prj_Ranged_Rocket_C::Water_Explosion_PS' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_Rocket_C, Explosion_Generic_PS) == 0x000718, "Member 'AB_Prj_Ranged_Rocket_C::Explosion_Generic_PS' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_Rocket_C, Explosion_Generic_PSC) == 0x000720, "Member 'AB_Prj_Ranged_Rocket_C::Explosion_Generic_PSC' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_Rocket_C, Rocket_Projectile_Explosion_Sound) == 0x000728, "Member 'AB_Prj_Ranged_Rocket_C::Rocket_Projectile_Explosion_Sound' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_Rocket_C, StopLocation) == 0x000730, "Member 'AB_Prj_Ranged_Rocket_C::StopLocation' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_Rocket_C, ObjectsToTraceAgainst) == 0x000740, "Member 'AB_Prj_Ranged_Rocket_C::ObjectsToTraceAgainst' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_Rocket_C, Explosion_Flesh_Damage_PS) == 0x000750, "Member 'AB_Prj_Ranged_Rocket_C::Explosion_Flesh_Damage_PS' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_Rocket_C, StopRotZ) == 0x000758, "Member 'AB_Prj_Ranged_Rocket_C::StopRotZ' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_Rocket_C, TrailLifetime) == 0x000764, "Member 'AB_Prj_Ranged_Rocket_C::TrailLifetime' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_Rocket_C, Explosion_Flesh_Damage_PSC) == 0x000768, "Member 'AB_Prj_Ranged_Rocket_C::Explosion_Flesh_Damage_PSC' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_Rocket_C, Rocket_Projectile_Explosion_Water_Sound) == 0x000770, "Member 'AB_Prj_Ranged_Rocket_C::Rocket_Projectile_Explosion_Water_Sound' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_Rocket_C, Rocket_Projectile_InAir_Sound) == 0x000778, "Member 'AB_Prj_Ranged_Rocket_C::Rocket_Projectile_InAir_Sound' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_Rocket_C, RocketTrailPS) == 0x000780, "Member 'AB_Prj_Ranged_Rocket_C::RocketTrailPS' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_Rocket_C, Tick_Delta) == 0x000788, "Member 'AB_Prj_Ranged_Rocket_C::Tick_Delta' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_Rocket_C, RocketSpinRate) == 0x00078C, "Member 'AB_Prj_Ranged_Rocket_C::RocketSpinRate' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_Rocket_C, Explosion_Impact_Offset) == 0x000790, "Member 'AB_Prj_Ranged_Rocket_C::Explosion_Impact_Offset' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_Rocket_C, RocketSpin) == 0x000794, "Member 'AB_Prj_Ranged_Rocket_C::RocketSpin' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_Rocket_C, RocketScale) == 0x0007A0, "Member 'AB_Prj_Ranged_Rocket_C::RocketScale' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_Rocket_C, TimerMaxReached_) == 0x0007AC, "Member 'AB_Prj_Ranged_Rocket_C::TimerMaxReached_' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_Rocket_C, Ground_Decal) == 0x0007B0, "Member 'AB_Prj_Ranged_Rocket_C::Ground_Decal' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_Rocket_C, Ground_Decal_MID) == 0x0007B8, "Member 'AB_Prj_Ranged_Rocket_C::Ground_Decal_MID' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_Rocket_C, Decal_Size_Max) == 0x0007C0, "Member 'AB_Prj_Ranged_Rocket_C::Decal_Size_Max' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_Rocket_C, Decal_Size_Min) == 0x0007C4, "Member 'AB_Prj_Ranged_Rocket_C::Decal_Size_Min' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_Rocket_C, DecalLocation) == 0x0007C8, "Member 'AB_Prj_Ranged_Rocket_C::DecalLocation' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_Rocket_C, Rocket_Trail_Template) == 0x0007D8, "Member 'AB_Prj_Ranged_Rocket_C::Rocket_Trail_Template' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_Rocket_C, SurfaceType) == 0x0007E0, "Member 'AB_Prj_Ranged_Rocket_C::SurfaceType' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_Rocket_C, Explosion_PS) == 0x0007E8, "Member 'AB_Prj_Ranged_Rocket_C::Explosion_PS' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_Rocket_C, ExplosionForceFeedbackNear) == 0x0007F0, "Member 'AB_Prj_Ranged_Rocket_C::ExplosionForceFeedbackNear' has a wrong offset!");
static_assert(offsetof(AB_Prj_Ranged_Rocket_C, ExplosionForceFeedbackFar) == 0x0007F8, "Member 'AB_Prj_Ranged_Rocket_C::ExplosionForceFeedbackFar' has a wrong offset!");

}

