#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_LockerList_Type

#include "Basic.hpp"


namespace SDK::Params
{

// Function BPI_LockerList_Type.BPI_LockerList_Type_C.BindPreviewActions
// 0x0008 (0x0008 - 0x0000)
struct BPI_LockerList_Type_C_BindPreviewActions final
{
public:
	class UFortItemPreviewWidget*                 Preview_Widget;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPI_LockerList_Type_C_BindPreviewActions) == 0x000008, "Wrong alignment on BPI_LockerList_Type_C_BindPreviewActions");
static_assert(sizeof(BPI_LockerList_Type_C_BindPreviewActions) == 0x000008, "Wrong size on BPI_LockerList_Type_C_BindPreviewActions");

// Function BPI_LockerList_Type.BPI_LockerList_Type_C.SetUpBinds
// 0x0010 (0x0010 - 0x0000)
struct BPI_LockerList_Type_C_SetUpBinds final
{
public:
	class UWidget*                                Widget;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UFortItemPreviewWidget*                 PreviewWidget;                                     // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPI_LockerList_Type_C_SetUpBinds) == 0x000008, "Wrong alignment on BPI_LockerList_Type_C_SetUpBinds");
static_assert(sizeof(BPI_LockerList_Type_C_SetUpBinds) == 0x000010, "Wrong size on BPI_LockerList_Type_C_SetUpBinds");

// Function BPI_LockerList_Type.BPI_LockerList_Type_C.SetupPreviewActionBinds
// 0x0008 (0x0008 - 0x0000)
struct BPI_LockerList_Type_C_SetupPreviewActionBinds final
{
public:
	class UFortItemPreviewWidget*                 PreviewWidget;                                     // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPI_LockerList_Type_C_SetupPreviewActionBinds) == 0x000008, "Wrong alignment on BPI_LockerList_Type_C_SetupPreviewActionBinds");
static_assert(sizeof(BPI_LockerList_Type_C_SetupPreviewActionBinds) == 0x000008, "Wrong size on BPI_LockerList_Type_C_SetupPreviewActionBinds");

// Function BPI_LockerList_Type.BPI_LockerList_Type_C.GetListView
// 0x0008 (0x0008 - 0x0000)
struct BPI_LockerList_Type_C_GetListView final
{
public:
	class UFortCommonTileView*                    TileView;                                          // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPI_LockerList_Type_C_GetListView) == 0x000008, "Wrong alignment on BPI_LockerList_Type_C_GetListView");
static_assert(sizeof(BPI_LockerList_Type_C_GetListView) == 0x000008, "Wrong size on BPI_LockerList_Type_C_GetListView");

}

