#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CRD_ClassSelectorUI

#include "Basic.hpp"

#include "FortniteUI_structs.hpp"
#include "CommonUI_classes.hpp"
#include "FortniteGame_structs.hpp"
#include "FortniteGame_classes.hpp"
#include "UMG_classes.hpp"
#include "SlateCore_structs.hpp"
#include "Engine_structs.hpp"
#include "CRD_ClassSelectorRuntime_structs.hpp"
#include "CoreUObject_classes.hpp"


namespace SDK
{

// Class CRD_ClassSelectorUI.ClassSelectorLoadoutContainer
// 0x0048 (0x0338 - 0x02F0)
class UClassSelectorLoadoutContainer final : public UCommonUserWidget
{
public:
	class UWrapBox*                               WrapBox;                                           // 0x02F0(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	TSubclassOf<class UAthenaItemElementWidgetBase> EntryWidgetClass;                                  // 0x02F8(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	TArray<class UAthenaItemElementWidgetBase*>   EntryWidgets;                                      // 0x0300(0x0010)(ExportObject, ZeroConstructor, Transient, ContainsInstancedReference, Protected, UObjectWrapper, NativeAccessSpecifierProtected)
	class UFortItemDefinition*                    PreviewItemDef;                                    // 0x0310(0x0008)(Edit, ZeroConstructor, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	int32                                         NumPreviewEntries;                                 // 0x0318(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_31C[0x1C];                                     // 0x031C(0x001C)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"ClassSelectorLoadoutContainer">();
	}
	static class UClassSelectorLoadoutContainer* GetDefaultObj()
	{
		return GetDefaultObjImpl<UClassSelectorLoadoutContainer>();
	}
};
static_assert(alignof(UClassSelectorLoadoutContainer) == 0x000008, "Wrong alignment on UClassSelectorLoadoutContainer");
static_assert(sizeof(UClassSelectorLoadoutContainer) == 0x000338, "Wrong size on UClassSelectorLoadoutContainer");

// Class CRD_ClassSelectorUI.ClassSelectorTabButtons
// 0x00B8 (0x03A8 - 0x02F0)
class UClassSelectorTabButtons final : public UCommonUserWidget
{
public:
	class UCommonActionWidget*                    LeftActionWidget;                                  // 0x02F0(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UCommonActionWidget*                    RightActionWidget;                                 // 0x02F8(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UScrollBox*                             TabButtonsScrollBox;                               // 0x0300(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UCommonButtonBase*                      LeftButton;                                        // 0x0308(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UCommonButtonBase*                      RightButton;                                       // 0x0310(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FDataTableRowHandle                    LeftInputAction;                                   // 0x0318(0x0010)(Edit, BlueprintVisible, NoDestructor, Protected, NativeAccessSpecifierProtected)
	uint8                                         Pad_328[0x8];                                      // 0x0328(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FDataTableRowHandle                    RightInputAction;                                  // 0x0330(0x0010)(Edit, BlueprintVisible, NoDestructor, Protected, NativeAccessSpecifierProtected)
	uint8                                         Pad_340[0x8];                                      // 0x0340(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UClassSelectorTeamTile*>         TabButtons;                                        // 0x0348(0x0010)(ExportObject, ZeroConstructor, Transient, ContainsInstancedReference, Protected, UObjectWrapper, NativeAccessSpecifierProtected)
	TSubclassOf<class UClassSelectorTeamTile>     TabButtonClass;                                    // 0x0358(0x0008)(Edit, ZeroConstructor, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FMargin                                TabButtonPadding;                                  // 0x0360(0x0010)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, NativeAccessSpecifierProtected)
	uint8                                         Pad_370[0x8];                                      // 0x0370(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FText>                           DesignerPreviewTabNames;                           // 0x0378(0x0010)(Edit, ZeroConstructor, Protected, NativeAccessSpecifierProtected)
	float                                         ButtonScrollAmount;                                // 0x0388(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_38C[0x1C];                                     // 0x038C(0x001C)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"ClassSelectorTabButtons">();
	}
	static class UClassSelectorTabButtons* GetDefaultObj()
	{
		return GetDefaultObjImpl<UClassSelectorTabButtons>();
	}
};
static_assert(alignof(UClassSelectorTabButtons) == 0x000008, "Wrong alignment on UClassSelectorTabButtons");
static_assert(sizeof(UClassSelectorTabButtons) == 0x0003A8, "Wrong size on UClassSelectorTabButtons");

// Class CRD_ClassSelectorUI.ClassSelectorTeamInfoWidget
// 0x0018 (0x02E0 - 0x02C8)
class UClassSelectorTeamInfoWidget final : public UUserWidget
{
public:
	class UCommonTextBlock*                       TeamName;                                          // 0x02C8(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UCommonTextBlock*                       TeamCountText;                                     // 0x02D0(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UCommonTextBlock*                       TeamDescription;                                   // 0x02D8(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"ClassSelectorTeamInfoWidget">();
	}
	static class UClassSelectorTeamInfoWidget* GetDefaultObj()
	{
		return GetDefaultObjImpl<UClassSelectorTeamInfoWidget>();
	}
};
static_assert(alignof(UClassSelectorTeamInfoWidget) == 0x000008, "Wrong alignment on UClassSelectorTeamInfoWidget");
static_assert(sizeof(UClassSelectorTeamInfoWidget) == 0x0002E0, "Wrong size on UClassSelectorTeamInfoWidget");

// Class CRD_ClassSelectorUI.CreativeClassSelectorButton
// 0x0040 (0x14E0 - 0x14A0)
class UCreativeClassSelectorButton : public UCommonButtonBase
{
public:
	class UCommonTextBlock*                       ButtonTextBlock;                                   // 0x14A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UCommonActionWidget*                    ActionWidget;                                      // 0x14A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class FText                                   ButtonText;                                        // 0x14B0(0x0010)(Edit, BlueprintVisible, Protected, NativeAccessSpecifierProtected)
	struct FDataTableRowHandle                    buttonInputAction;                                 // 0x14C0(0x0010)(Edit, BlueprintVisible, NoDestructor, Protected, NativeAccessSpecifierProtected)
	bool                                          bAutoCapitalize;                                   // 0x14D0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_14D1[0xF];                                     // 0x14D1(0x000F)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void SetButtonText(const class FText& InText);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"CreativeClassSelectorButton">();
	}
	static class UCreativeClassSelectorButton* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCreativeClassSelectorButton>();
	}
};
static_assert(alignof(UCreativeClassSelectorButton) == 0x000010, "Wrong alignment on UCreativeClassSelectorButton");
static_assert(sizeof(UCreativeClassSelectorButton) == 0x0014E0, "Wrong size on UCreativeClassSelectorButton");

// Class CRD_ClassSelectorUI.ClassSelectorTeamTile
// 0x0090 (0x1570 - 0x14E0)
class UClassSelectorTeamTile final : public UCreativeClassSelectorButton
{
public:
	uint8                                         Pad_14E0[0x78];                                    // 0x14E0(0x0078)(Fixing Size After Last Property [ Dumper-7 ])
	class UTextBlock*                             PlayerCount;                                       // 0x1558(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UCommonLazyImage*                       TeamIconImage;                                     // 0x1560(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_1568[0x8];                                     // 0x1568(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void OnPlayerCountSet(int32 NewPlayerCount);
	void OnTeamColorIndexSet(int32 TeamColorIndex);
	void OnTeamIconSet(const struct FCreativeIconOption& NewTeamIcon);
	void OnTeamSet(const struct FMinigameTeam& NewTeamData);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"ClassSelectorTeamTile">();
	}
	static class UClassSelectorTeamTile* GetDefaultObj()
	{
		return GetDefaultObjImpl<UClassSelectorTeamTile>();
	}
};
static_assert(alignof(UClassSelectorTeamTile) == 0x000010, "Wrong alignment on UClassSelectorTeamTile");
static_assert(sizeof(UClassSelectorTeamTile) == 0x001570, "Wrong size on UClassSelectorTeamTile");

// Class CRD_ClassSelectorUI.ClassSelectorTeamTiles
// 0x0048 (0x0338 - 0x02F0)
class UClassSelectorTeamTiles final : public UCommonUserWidget
{
public:
	uint8                                         Pad_2F0[0x8];                                      // 0x02F0(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UClassSelectorTeamTile*>         TeamTiles;                                         // 0x02F8(0x0010)(ExportObject, ZeroConstructor, Transient, ContainsInstancedReference, Protected, UObjectWrapper, NativeAccessSpecifierProtected)
	class UUniformGridPanel*                      RootPanel;                                         // 0x0308(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	TSubclassOf<class UClassSelectorTeamTile>     EntryClass;                                        // 0x0310(0x0008)(Edit, ZeroConstructor, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	int32                                         DesignerPreviewEntries;                            // 0x0318(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_31C[0x1C];                                     // 0x031C(0x001C)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"ClassSelectorTeamTiles">();
	}
	static class UClassSelectorTeamTiles* GetDefaultObj()
	{
		return GetDefaultObjImpl<UClassSelectorTeamTiles>();
	}
};
static_assert(alignof(UClassSelectorTeamTiles) == 0x000008, "Wrong alignment on UClassSelectorTeamTiles");
static_assert(sizeof(UClassSelectorTeamTiles) == 0x000338, "Wrong size on UClassSelectorTeamTiles");

// Class CRD_ClassSelectorUI.CreativeClassItemInfo
// 0x0048 (0x0070 - 0x0028)
class UCreativeClassItemInfo final : public UObject
{
public:
	struct FMinigameClassSlot                     ClassSlot;                                         // 0x0028(0x0040)(Transient, NativeAccessSpecifierPublic)
	uint8                                         Pad_68[0x8];                                       // 0x0068(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"CreativeClassItemInfo">();
	}
	static class UCreativeClassItemInfo* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCreativeClassItemInfo>();
	}
};
static_assert(alignof(UCreativeClassItemInfo) == 0x000008, "Wrong alignment on UCreativeClassItemInfo");
static_assert(sizeof(UCreativeClassItemInfo) == 0x000070, "Wrong size on UCreativeClassItemInfo");

// Class CRD_ClassSelectorUI.CreativeClassEntry
// 0x0010 (0x14F0 - 0x14E0)
class UCreativeClassEntry final : public UCreativeClassSelectorButton
{
public:
	class UCreativeClassItemInfo*                 ItemInfo;                                          // 0x14E0(0x0008)(ZeroConstructor, Transient, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_14E8[0x8];                                     // 0x14E8(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void OnBrowsingLoadout(const bool bBrowsingLoadout);
	void OnClassEntryDataSet(const bool bIsCurrentClass, const bool bIsPendingClass);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"CreativeClassEntry">();
	}
	static class UCreativeClassEntry* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCreativeClassEntry>();
	}
};
static_assert(alignof(UCreativeClassEntry) == 0x000010, "Wrong alignment on UCreativeClassEntry");
static_assert(sizeof(UCreativeClassEntry) == 0x0014F0, "Wrong size on UCreativeClassEntry");

// Class CRD_ClassSelectorUI.CreativeClassSelector
// 0x0138 (0x0540 - 0x0408)
class UCreativeClassSelector final : public UCommonActivatableWidget
{
public:
	uint8                                         Pad_408[0x10];                                     // 0x0408(0x0010)(Fixing Size After Last Property [ Dumper-7 ])
	class UClassSelectorTabButtons*               TabButtons_TeamSelection;                          // 0x0418(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UCommonListView*                        ListView_Classes;                                  // 0x0420(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	TArray<class UCreativeClassItemInfo*>         ClassItemInfos;                                    // 0x0428(0x0010)(ZeroConstructor, Protected, UObjectWrapper, NativeAccessSpecifierProtected)
	class UScrollBox*                             LoadoutScrollBox;                                  // 0x0438(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UClassSelectorLoadoutContainer*         LoadoutContainer_Inventory;                        // 0x0440(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UClassSelectorLoadoutContainer*         LoadoutContainer_Resources;                        // 0x0448(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UCommonButtonBase*                      Button_SelectLoadout;                              // 0x0450(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UCommonButtonBase*                      Button_RandomClass;                                // 0x0458(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UWidgetSwitcher*                        Switcher_Descriptions;                             // 0x0460(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UPanelWidget*                           ClassAndTeamDescriptionContainer;                  // 0x0468(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UPanelWidget*                           ItemDescriptionContainer;                          // 0x0470(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UPanelWidget*                           InventoryPanel;                                    // 0x0478(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UPanelWidget*                           ResourcesPanel;                                    // 0x0480(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UCommonTextBlock*                       ItemRarity;                                        // 0x0488(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UCommonTextBlock*                       ItemName;                                          // 0x0490(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UCommonTextBlock*                       ItemDescription;                                   // 0x0498(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UPanelWidget*                           TeamDescriptionContainer;                          // 0x04A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UClassSelectorTeamInfoWidget*           TeamInfoWidget_FullView;                           // 0x04A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UClassSelectorTeamInfoWidget*           TeamInfoWidget_TeamsOnly;                          // 0x04B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UWidgetSwitcher*                        DisplaySwitcher;                                   // 0x04B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UPanelWidget*                           ClassAndTeamSelectionContainer;                    // 0x04C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UPanelWidget*                           OnlyTeamSelectionContainer;                        // 0x04C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UPanelWidget*                           InvalidDataContainer;                              // 0x04D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UClassSelectorTeamTiles*                TeamTiles;                                         // 0x04D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	TSubclassOf<class UCreativeClassSelectorButton> TeamSelectionTabClass;                             // 0x04E0(0x0008)(Edit, ZeroConstructor, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bIsModalVersion;                                   // 0x04E8(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bEnableModalTimeLimit;                             // 0x04E9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_4EA[0x2];                                      // 0x04EA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         ModalTimeLimitInSeconds;                           // 0x04EC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_4F0[0x10];                                     // 0x04F0(0x0010)(Fixing Size After Last Property [ Dumper-7 ])
	EClassSelectorDisplayMode                     DisplayMode;                                       // 0x0500(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bDeferRespawn;                                     // 0x0501(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_502[0x6];                                      // 0x0502(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FDataTableRowHandle                    ReturnToClassSelectionInputAction;                 // 0x0508(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, NoDestructor, Protected, NativeAccessSpecifierProtected)
	float                                         LoadoutScrollPadding;                              // 0x0518(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_51C[0x1C];                                     // 0x051C(0x001C)(Fixing Size After Last Property [ Dumper-7 ])
	class UCreativeClassItemInfo*                 SelectedClassItemInfo;                             // 0x0538(0x0008)(ZeroConstructor, Transient, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	void HandleMinigameStateChanged(class AFortMinigame* Minigame, EFortMinigameState MinigameState);
	void OnClassSelectionChanged(const class FText& NewClassName, const class FText& NewClassDescription);
	void OnClassSelectorUIPopulated(const bool bHasValidData);
	void OnLoadoutCommitted(const class FText& NewClassName, const class FText& NewTeamName, const bool bNewLoadout, const bool bDefer, uint8 SelectedClassIndex);
	void OnTimerCountdown(const int32 RemainingTime);

	class UWidget* GetFirstLoadoutItem() const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"CreativeClassSelector">();
	}
	static class UCreativeClassSelector* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCreativeClassSelector>();
	}
};
static_assert(alignof(UCreativeClassSelector) == 0x000008, "Wrong alignment on UCreativeClassSelector");
static_assert(sizeof(UCreativeClassSelector) == 0x000540, "Wrong size on UCreativeClassSelector");

// Class CRD_ClassSelectorUI.CreativeClassSelectorMapTab
// 0x0070 (0x0478 - 0x0408)
class UCreativeClassSelectorMapTab final : public UCommonActivatableWidget
{
public:
	uint8                                         Pad_408[0x28];                                     // 0x0408(0x0028)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAthenaMapScreenContainerTabInfo       MapTabInfo;                                        // 0x0430(0x0040)(Edit, NativeAccessSpecifierPublic)
	class UCreativeClassSelector*                 CreativeClassSelector;                             // 0x0470(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void SetTabName(const class FText& TabName);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"CreativeClassSelectorMapTab">();
	}
	static class UCreativeClassSelectorMapTab* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCreativeClassSelectorMapTab>();
	}
};
static_assert(alignof(UCreativeClassSelectorMapTab) == 0x000008, "Wrong alignment on UCreativeClassSelectorMapTab");
static_assert(sizeof(UCreativeClassSelectorMapTab) == 0x000478, "Wrong size on UCreativeClassSelectorMapTab");

// Class CRD_ClassSelectorUI.Mutator_ClassSelectorUI
// 0x0000 (0x0338 - 0x0338)
class AMutator_ClassSelectorUI final : public AFortAthenaMutator
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Mutator_ClassSelectorUI">();
	}
	static class AMutator_ClassSelectorUI* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMutator_ClassSelectorUI>();
	}
};
static_assert(alignof(AMutator_ClassSelectorUI) == 0x000008, "Wrong alignment on AMutator_ClassSelectorUI");
static_assert(sizeof(AMutator_ClassSelectorUI) == 0x000338, "Wrong size on AMutator_ClassSelectorUI");

}

