#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CustomControlsUI

#include "Basic.hpp"

#include "CustomControlsUI_classes.hpp"
#include "CustomControlsUI_parameters.hpp"


namespace SDK
{

// Function CustomControlsUI.CustomControlsUIDirector.BP_OnOptionsActivated
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UCustomControlOptions_Base*       Options                                                (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ACustomControlsUIDirector::BP_OnOptionsActivated(const class UCustomControlOptions_Base* Options)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomControlsUIDirector", "BP_OnOptionsActivated");

	Params::CustomControlsUIDirector_BP_OnOptionsActivated Parms{};

	Parms.Options = Options;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CustomControlsUI.CustomControlsUIDirector.BP_OnOptionsDeactivated
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UCustomControlOptions_Base*       Options                                                (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ACustomControlsUIDirector::BP_OnOptionsDeactivated(const class UCustomControlOptions_Base* Options)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomControlsUIDirector", "BP_OnOptionsDeactivated");

	Params::CustomControlsUIDirector_BP_OnOptionsDeactivated Parms{};

	Parms.Options = Options;

	UObject::ProcessEvent(Func, &Parms);
}

}

