#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DashRuntime

#include "Basic.hpp"

#include "DashRuntime_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "FortniteGame_structs.hpp"


namespace SDK::Params
{

// Function DashRuntime.FortGameplayAbility_Dash.GetDashTarget
// 0x0018 (0x0018 - 0x0000)
struct FortGameplayAbility_Dash_GetDashTarget final
{
public:
	struct FVector                                ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FortGameplayAbility_Dash_GetDashTarget) == 0x000008, "Wrong alignment on FortGameplayAbility_Dash_GetDashTarget");
static_assert(sizeof(FortGameplayAbility_Dash_GetDashTarget) == 0x000018, "Wrong size on FortGameplayAbility_Dash_GetDashTarget");

// Function DashRuntime.FortGameplayAbility_Dash.GetEndMovementVelocity
// 0x0018 (0x0018 - 0x0000)
struct FortGameplayAbility_Dash_GetEndMovementVelocity final
{
public:
	struct FVector                                ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FortGameplayAbility_Dash_GetEndMovementVelocity) == 0x000008, "Wrong alignment on FortGameplayAbility_Dash_GetEndMovementVelocity");
static_assert(sizeof(FortGameplayAbility_Dash_GetEndMovementVelocity) == 0x000018, "Wrong size on FortGameplayAbility_Dash_GetEndMovementVelocity");

// Function DashRuntime.FortGameplayAbility_Dash.GetMoveDistance
// 0x0004 (0x0004 - 0x0000)
struct FortGameplayAbility_Dash_GetMoveDistance final
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FortGameplayAbility_Dash_GetMoveDistance) == 0x000004, "Wrong alignment on FortGameplayAbility_Dash_GetMoveDistance");
static_assert(sizeof(FortGameplayAbility_Dash_GetMoveDistance) == 0x000004, "Wrong size on FortGameplayAbility_Dash_GetMoveDistance");

// Function DashRuntime.FortMovementMode_ExtDash.TryActivateDashMME
// 0x0070 (0x0070 - 0x0000)
struct FortMovementMode_ExtDash_TryActivateDashMME final
{
public:
	class AFortPawn*                              TargetPawn;                                        // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSubclassOf<class UFortMovementMode_ExtDash>  DashMME;                                           // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FFortMovementMode_DashCreationData     CreationData;                                      // 0x0010(0x0058)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0068(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_69[0x7];                                       // 0x0069(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FortMovementMode_ExtDash_TryActivateDashMME) == 0x000008, "Wrong alignment on FortMovementMode_ExtDash_TryActivateDashMME");
static_assert(sizeof(FortMovementMode_ExtDash_TryActivateDashMME) == 0x000070, "Wrong size on FortMovementMode_ExtDash_TryActivateDashMME");

// Function DashRuntime.FortMovementMode_ExtDash.BP_UpdateBeforeCharacterMovement
// 0x0008 (0x0008 - 0x0000)
struct FortMovementMode_ExtDash_BP_UpdateBeforeCharacterMovement final
{
public:
	float                                         DeltaTime;                                         // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EFortMovementModeExt_UpdateResult             ReturnValue;                                       // 0x0004(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FortMovementMode_ExtDash_BP_UpdateBeforeCharacterMovement) == 0x000004, "Wrong alignment on FortMovementMode_ExtDash_BP_UpdateBeforeCharacterMovement");
static_assert(sizeof(FortMovementMode_ExtDash_BP_UpdateBeforeCharacterMovement) == 0x000008, "Wrong size on FortMovementMode_ExtDash_BP_UpdateBeforeCharacterMovement");

}

