#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FabricUI

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "UMG_structs.hpp"


namespace SDK::Params
{

// Function FabricUI.FabricScreenWidget.AttachFabricWidget
// 0x0020 (0x0020 - 0x0000)
struct FabricScreenWidget_AttachFabricWidget final
{
public:
	TSubclassOf<class UFabricWidget>              FabricWidgetClass;                                 // 0x0000(0x0008)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector2D                              GridPosition;                                      // 0x0008(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UFabricWidget*                          ReturnValue;                                       // 0x0018(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FabricScreenWidget_AttachFabricWidget) == 0x000008, "Wrong alignment on FabricScreenWidget_AttachFabricWidget");
static_assert(sizeof(FabricScreenWidget_AttachFabricWidget) == 0x000020, "Wrong size on FabricScreenWidget_AttachFabricWidget");

// Function FabricUI.FabricScreenWidget.SetScreenGridDimensions
// 0x0010 (0x0010 - 0x0000)
struct FabricScreenWidget_SetScreenGridDimensions final
{
public:
	struct FVector2D                              InNewDimensions;                                   // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FabricScreenWidget_SetScreenGridDimensions) == 0x000008, "Wrong alignment on FabricScreenWidget_SetScreenGridDimensions");
static_assert(sizeof(FabricScreenWidget_SetScreenGridDimensions) == 0x000010, "Wrong size on FabricScreenWidget_SetScreenGridDimensions");

// Function FabricUI.FabricWidget.GetFabricViewModel
// 0x0008 (0x0008 - 0x0000)
struct FabricWidget_GetFabricViewModel final
{
public:
	class UFabricInteractableViewModel*           ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FabricWidget_GetFabricViewModel) == 0x000008, "Wrong alignment on FabricWidget_GetFabricViewModel");
static_assert(sizeof(FabricWidget_GetFabricViewModel) == 0x000008, "Wrong size on FabricWidget_GetFabricViewModel");

// Function FabricUI.FabricWidgetComponent.SetShouldSuscribeToSignificanceSubsystem
// 0x0001 (0x0001 - 0x0000)
struct FabricWidgetComponent_SetShouldSuscribeToSignificanceSubsystem final
{
public:
	bool                                          ShouldSuscribe;                                    // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FabricWidgetComponent_SetShouldSuscribeToSignificanceSubsystem) == 0x000001, "Wrong alignment on FabricWidgetComponent_SetShouldSuscribeToSignificanceSubsystem");
static_assert(sizeof(FabricWidgetComponent_SetShouldSuscribeToSignificanceSubsystem) == 0x000001, "Wrong size on FabricWidgetComponent_SetShouldSuscribeToSignificanceSubsystem");

// Function FabricUI.FabricWidgetComponent.GetTickMode
// 0x0001 (0x0001 - 0x0000)
struct FabricWidgetComponent_GetTickMode final
{
public:
	ETickMode                                     ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FabricWidgetComponent_GetTickMode) == 0x000001, "Wrong alignment on FabricWidgetComponent_GetTickMode");
static_assert(sizeof(FabricWidgetComponent_GetTickMode) == 0x000001, "Wrong size on FabricWidgetComponent_GetTickMode");

// Function FabricUI.FabricWidgetTickControlSubsystem.RegisterFabricWidgetComponent
// 0x0008 (0x0008 - 0x0000)
struct FabricWidgetTickControlSubsystem_RegisterFabricWidgetComponent final
{
public:
	class UFabricWidgetComponent*                 WidgetComponent;                                   // 0x0000(0x0008)(Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FabricWidgetTickControlSubsystem_RegisterFabricWidgetComponent) == 0x000008, "Wrong alignment on FabricWidgetTickControlSubsystem_RegisterFabricWidgetComponent");
static_assert(sizeof(FabricWidgetTickControlSubsystem_RegisterFabricWidgetComponent) == 0x000008, "Wrong size on FabricWidgetTickControlSubsystem_RegisterFabricWidgetComponent");

// Function FabricUI.FabricWidgetTickControlSubsystem.UnregisterFabricWidgetComponent
// 0x0008 (0x0008 - 0x0000)
struct FabricWidgetTickControlSubsystem_UnregisterFabricWidgetComponent final
{
public:
	class UFabricWidgetComponent*                 WidgetComponent;                                   // 0x0000(0x0008)(Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FabricWidgetTickControlSubsystem_UnregisterFabricWidgetComponent) == 0x000008, "Wrong alignment on FabricWidgetTickControlSubsystem_UnregisterFabricWidgetComponent");
static_assert(sizeof(FabricWidgetTickControlSubsystem_UnregisterFabricWidgetComponent) == 0x000008, "Wrong size on FabricWidgetTickControlSubsystem_UnregisterFabricWidgetComponent");

}

