#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FNE_VolumeRuntime

#include "Basic.hpp"


namespace SDK
{

// Enum FNE_VolumeRuntime.EFNEVolumeShapeTypeEnum
// NumValues: 0x0005
enum class EFNEVolumeShapeTypeEnum : uint8
{
	BoxVolume                                = 0,
	CylinderVolume                           = 1,
	SphereVolume                             = 2,
	CustomVolume                             = 3,
	EFNEVolumeShapeTypeEnum_MAX              = 4,
};

// Enum FNE_VolumeRuntime.EVolumeEnableOverlapBehavior
// NumValues: 0x0004
enum class EVolumeEnableOverlapBehavior : uint8
{
	Never                                    = 0,
	Game                                     = 1,
	Always                                   = 2,
	EVolumeEnableOverlapBehavior_MAX         = 3,
};

}

