#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GameFeatures

#include "Basic.hpp"


namespace SDK::Params
{

// Function GameFeatures.GameFeatureData.GetPluginName
// 0x0018 (0x0018 - 0x0000)
struct GameFeatureData_GetPluginName final
{
public:
	const class UGameFeatureData*                 GFD;                                               // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 PluginName;                                        // 0x0008(0x0010)(Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(GameFeatureData_GetPluginName) == 0x000008, "Wrong alignment on GameFeatureData_GetPluginName");
static_assert(sizeof(GameFeatureData_GetPluginName) == 0x000018, "Wrong size on GameFeatureData_GetPluginName");

}

