#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCL_Carmine_Beam_Loop

#include "Basic.hpp"

#include "GameplayAbilities_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function GCL_Carmine_Beam_Loop.GCL_Carmine_Beam_Loop_C.ExecuteUbergraph_GCL_Carmine_Beam_Loop
// 0x00D8 (0x00D8 - 0x0000)
struct GCL_Carmine_Beam_Loop_C_ExecuteUbergraph_GCL_Carmine_Beam_Loop final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 K2Node_Event_MyTarget;                             // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EGameplayCueEvent                             K2Node_Event_EventType;                            // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayCueParameters                 K2Node_Event_Parameters;                           // 0x0018(0x00B8)(ConstParm, ContainsInstancedReference)
	EEndPlayReason                                K2Node_Event_EndPlayReason;                        // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GCL_Carmine_Beam_Loop_C_ExecuteUbergraph_GCL_Carmine_Beam_Loop) == 0x000008, "Wrong alignment on GCL_Carmine_Beam_Loop_C_ExecuteUbergraph_GCL_Carmine_Beam_Loop");
static_assert(sizeof(GCL_Carmine_Beam_Loop_C_ExecuteUbergraph_GCL_Carmine_Beam_Loop) == 0x0000D8, "Wrong size on GCL_Carmine_Beam_Loop_C_ExecuteUbergraph_GCL_Carmine_Beam_Loop");
static_assert(offsetof(GCL_Carmine_Beam_Loop_C_ExecuteUbergraph_GCL_Carmine_Beam_Loop, EntryPoint) == 0x000000, "Member 'GCL_Carmine_Beam_Loop_C_ExecuteUbergraph_GCL_Carmine_Beam_Loop::EntryPoint' has a wrong offset!");
static_assert(offsetof(GCL_Carmine_Beam_Loop_C_ExecuteUbergraph_GCL_Carmine_Beam_Loop, K2Node_Event_MyTarget) == 0x000008, "Member 'GCL_Carmine_Beam_Loop_C_ExecuteUbergraph_GCL_Carmine_Beam_Loop::K2Node_Event_MyTarget' has a wrong offset!");
static_assert(offsetof(GCL_Carmine_Beam_Loop_C_ExecuteUbergraph_GCL_Carmine_Beam_Loop, K2Node_Event_EventType) == 0x000010, "Member 'GCL_Carmine_Beam_Loop_C_ExecuteUbergraph_GCL_Carmine_Beam_Loop::K2Node_Event_EventType' has a wrong offset!");
static_assert(offsetof(GCL_Carmine_Beam_Loop_C_ExecuteUbergraph_GCL_Carmine_Beam_Loop, K2Node_Event_Parameters) == 0x000018, "Member 'GCL_Carmine_Beam_Loop_C_ExecuteUbergraph_GCL_Carmine_Beam_Loop::K2Node_Event_Parameters' has a wrong offset!");
static_assert(offsetof(GCL_Carmine_Beam_Loop_C_ExecuteUbergraph_GCL_Carmine_Beam_Loop, K2Node_Event_EndPlayReason) == 0x0000D0, "Member 'GCL_Carmine_Beam_Loop_C_ExecuteUbergraph_GCL_Carmine_Beam_Loop::K2Node_Event_EndPlayReason' has a wrong offset!");

// Function GCL_Carmine_Beam_Loop.GCL_Carmine_Beam_Loop_C.K2_HandleGameplayCue
// 0x00C8 (0x00C8 - 0x0000)
struct GCL_Carmine_Beam_Loop_C_K2_HandleGameplayCue final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EGameplayCueEvent                             EventType;                                         // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayCueParameters                 Parameters;                                        // 0x0010(0x00B8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(GCL_Carmine_Beam_Loop_C_K2_HandleGameplayCue) == 0x000008, "Wrong alignment on GCL_Carmine_Beam_Loop_C_K2_HandleGameplayCue");
static_assert(sizeof(GCL_Carmine_Beam_Loop_C_K2_HandleGameplayCue) == 0x0000C8, "Wrong size on GCL_Carmine_Beam_Loop_C_K2_HandleGameplayCue");
static_assert(offsetof(GCL_Carmine_Beam_Loop_C_K2_HandleGameplayCue, MyTarget) == 0x000000, "Member 'GCL_Carmine_Beam_Loop_C_K2_HandleGameplayCue::MyTarget' has a wrong offset!");
static_assert(offsetof(GCL_Carmine_Beam_Loop_C_K2_HandleGameplayCue, EventType) == 0x000008, "Member 'GCL_Carmine_Beam_Loop_C_K2_HandleGameplayCue::EventType' has a wrong offset!");
static_assert(offsetof(GCL_Carmine_Beam_Loop_C_K2_HandleGameplayCue, Parameters) == 0x000010, "Member 'GCL_Carmine_Beam_Loop_C_K2_HandleGameplayCue::Parameters' has a wrong offset!");

// Function GCL_Carmine_Beam_Loop.GCL_Carmine_Beam_Loop_C.ReceiveEndPlay
// 0x0001 (0x0001 - 0x0000)
struct GCL_Carmine_Beam_Loop_C_ReceiveEndPlay final
{
public:
	EEndPlayReason                                EndPlayReason;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GCL_Carmine_Beam_Loop_C_ReceiveEndPlay) == 0x000001, "Wrong alignment on GCL_Carmine_Beam_Loop_C_ReceiveEndPlay");
static_assert(sizeof(GCL_Carmine_Beam_Loop_C_ReceiveEndPlay) == 0x000001, "Wrong size on GCL_Carmine_Beam_Loop_C_ReceiveEndPlay");
static_assert(offsetof(GCL_Carmine_Beam_Loop_C_ReceiveEndPlay, EndPlayReason) == 0x000000, "Member 'GCL_Carmine_Beam_Loop_C_ReceiveEndPlay::EndPlayReason' has a wrong offset!");

// Function GCL_Carmine_Beam_Loop.GCL_Carmine_Beam_Loop_C.WhileActive
// 0x00F8 (0x00F8 - 0x0000)
struct GCL_Carmine_Beam_Loop_C_WhileActive final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x00B8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	bool                                          ReturnValue;                                       // 0x00C0(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C1[0x7];                                       // 0x00C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerPawn_Athena_C*                   K2Node_DynamicCast_AsPlayer_Pawn_Athena;           // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_D1[0x3];                                       // 0x00D1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x00D4(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        CallFunc_SpawnSoundAtLocation_ReturnValue;         // 0x00E0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               CallFunc_SpawnEmitterAttached_ReturnValue;         // 0x00E8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(GCL_Carmine_Beam_Loop_C_WhileActive) == 0x000008, "Wrong alignment on GCL_Carmine_Beam_Loop_C_WhileActive");
static_assert(sizeof(GCL_Carmine_Beam_Loop_C_WhileActive) == 0x0000F8, "Wrong size on GCL_Carmine_Beam_Loop_C_WhileActive");
static_assert(offsetof(GCL_Carmine_Beam_Loop_C_WhileActive, MyTarget) == 0x000000, "Member 'GCL_Carmine_Beam_Loop_C_WhileActive::MyTarget' has a wrong offset!");
static_assert(offsetof(GCL_Carmine_Beam_Loop_C_WhileActive, Parameters) == 0x000008, "Member 'GCL_Carmine_Beam_Loop_C_WhileActive::Parameters' has a wrong offset!");
static_assert(offsetof(GCL_Carmine_Beam_Loop_C_WhileActive, ReturnValue) == 0x0000C0, "Member 'GCL_Carmine_Beam_Loop_C_WhileActive::ReturnValue' has a wrong offset!");
static_assert(offsetof(GCL_Carmine_Beam_Loop_C_WhileActive, K2Node_DynamicCast_AsPlayer_Pawn_Athena) == 0x0000C8, "Member 'GCL_Carmine_Beam_Loop_C_WhileActive::K2Node_DynamicCast_AsPlayer_Pawn_Athena' has a wrong offset!");
static_assert(offsetof(GCL_Carmine_Beam_Loop_C_WhileActive, K2Node_DynamicCast_bSuccess) == 0x0000D0, "Member 'GCL_Carmine_Beam_Loop_C_WhileActive::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(GCL_Carmine_Beam_Loop_C_WhileActive, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x0000D4, "Member 'GCL_Carmine_Beam_Loop_C_WhileActive::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCL_Carmine_Beam_Loop_C_WhileActive, CallFunc_SpawnSoundAtLocation_ReturnValue) == 0x0000E0, "Member 'GCL_Carmine_Beam_Loop_C_WhileActive::CallFunc_SpawnSoundAtLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCL_Carmine_Beam_Loop_C_WhileActive, CallFunc_SpawnEmitterAttached_ReturnValue) == 0x0000E8, "Member 'GCL_Carmine_Beam_Loop_C_WhileActive::CallFunc_SpawnEmitterAttached_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCL_Carmine_Beam_Loop_C_WhileActive, CallFunc_IsValid_ReturnValue) == 0x0000F0, "Member 'GCL_Carmine_Beam_Loop_C_WhileActive::CallFunc_IsValid_ReturnValue' has a wrong offset!");

// Function GCL_Carmine_Beam_Loop.GCL_Carmine_Beam_Loop_C.OnRemove
// 0x00C8 (0x00C8 - 0x0000)
struct GCL_Carmine_Beam_Loop_C_OnRemove final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x00B8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	bool                                          ReturnValue;                                       // 0x00C0(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00C1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(GCL_Carmine_Beam_Loop_C_OnRemove) == 0x000008, "Wrong alignment on GCL_Carmine_Beam_Loop_C_OnRemove");
static_assert(sizeof(GCL_Carmine_Beam_Loop_C_OnRemove) == 0x0000C8, "Wrong size on GCL_Carmine_Beam_Loop_C_OnRemove");
static_assert(offsetof(GCL_Carmine_Beam_Loop_C_OnRemove, MyTarget) == 0x000000, "Member 'GCL_Carmine_Beam_Loop_C_OnRemove::MyTarget' has a wrong offset!");
static_assert(offsetof(GCL_Carmine_Beam_Loop_C_OnRemove, Parameters) == 0x000008, "Member 'GCL_Carmine_Beam_Loop_C_OnRemove::Parameters' has a wrong offset!");
static_assert(offsetof(GCL_Carmine_Beam_Loop_C_OnRemove, ReturnValue) == 0x0000C0, "Member 'GCL_Carmine_Beam_Loop_C_OnRemove::ReturnValue' has a wrong offset!");
static_assert(offsetof(GCL_Carmine_Beam_Loop_C_OnRemove, CallFunc_IsValid_ReturnValue) == 0x0000C1, "Member 'GCL_Carmine_Beam_Loop_C_OnRemove::CallFunc_IsValid_ReturnValue' has a wrong offset!");

// Function GCL_Carmine_Beam_Loop.GCL_Carmine_Beam_Loop_C.OnWhileActiveParticleSystemActivate
// 0x00C0 (0x00C0 - 0x0000)
struct GCL_Carmine_Beam_Loop_C_OnWhileActiveParticleSystemActivate final
{
public:
	class UParticleSystemComponent*               WhileActiveParticleSysComponent;                   // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x00B8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(GCL_Carmine_Beam_Loop_C_OnWhileActiveParticleSystemActivate) == 0x000008, "Wrong alignment on GCL_Carmine_Beam_Loop_C_OnWhileActiveParticleSystemActivate");
static_assert(sizeof(GCL_Carmine_Beam_Loop_C_OnWhileActiveParticleSystemActivate) == 0x0000C0, "Wrong size on GCL_Carmine_Beam_Loop_C_OnWhileActiveParticleSystemActivate");
static_assert(offsetof(GCL_Carmine_Beam_Loop_C_OnWhileActiveParticleSystemActivate, WhileActiveParticleSysComponent) == 0x000000, "Member 'GCL_Carmine_Beam_Loop_C_OnWhileActiveParticleSystemActivate::WhileActiveParticleSysComponent' has a wrong offset!");
static_assert(offsetof(GCL_Carmine_Beam_Loop_C_OnWhileActiveParticleSystemActivate, Parameters) == 0x000008, "Member 'GCL_Carmine_Beam_Loop_C_OnWhileActiveParticleSystemActivate::Parameters' has a wrong offset!");

// Function GCL_Carmine_Beam_Loop.GCL_Carmine_Beam_Loop_C.OnStopParticleSystemSpawned
// 0x00C0 (0x00C0 - 0x0000)
struct GCL_Carmine_Beam_Loop_C_OnStopParticleSystemSpawned final
{
public:
	class UParticleSystemComponent*               SpawnedParticleSysComponent;                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x00B8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(GCL_Carmine_Beam_Loop_C_OnStopParticleSystemSpawned) == 0x000008, "Wrong alignment on GCL_Carmine_Beam_Loop_C_OnStopParticleSystemSpawned");
static_assert(sizeof(GCL_Carmine_Beam_Loop_C_OnStopParticleSystemSpawned) == 0x0000C0, "Wrong size on GCL_Carmine_Beam_Loop_C_OnStopParticleSystemSpawned");
static_assert(offsetof(GCL_Carmine_Beam_Loop_C_OnStopParticleSystemSpawned, SpawnedParticleSysComponent) == 0x000000, "Member 'GCL_Carmine_Beam_Loop_C_OnStopParticleSystemSpawned::SpawnedParticleSysComponent' has a wrong offset!");
static_assert(offsetof(GCL_Carmine_Beam_Loop_C_OnStopParticleSystemSpawned, Parameters) == 0x000008, "Member 'GCL_Carmine_Beam_Loop_C_OnStopParticleSystemSpawned::Parameters' has a wrong offset!");

// Function GCL_Carmine_Beam_Loop.GCL_Carmine_Beam_Loop_C.OnWhileActiveParticleSystemDeactivate
// 0x00C0 (0x00C0 - 0x0000)
struct GCL_Carmine_Beam_Loop_C_OnWhileActiveParticleSystemDeactivate final
{
public:
	class UParticleSystemComponent*               WhileActiveParticleSysComponent;                   // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x00B8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(GCL_Carmine_Beam_Loop_C_OnWhileActiveParticleSystemDeactivate) == 0x000008, "Wrong alignment on GCL_Carmine_Beam_Loop_C_OnWhileActiveParticleSystemDeactivate");
static_assert(sizeof(GCL_Carmine_Beam_Loop_C_OnWhileActiveParticleSystemDeactivate) == 0x0000C0, "Wrong size on GCL_Carmine_Beam_Loop_C_OnWhileActiveParticleSystemDeactivate");
static_assert(offsetof(GCL_Carmine_Beam_Loop_C_OnWhileActiveParticleSystemDeactivate, WhileActiveParticleSysComponent) == 0x000000, "Member 'GCL_Carmine_Beam_Loop_C_OnWhileActiveParticleSystemDeactivate::WhileActiveParticleSysComponent' has a wrong offset!");
static_assert(offsetof(GCL_Carmine_Beam_Loop_C_OnWhileActiveParticleSystemDeactivate, Parameters) == 0x000008, "Member 'GCL_Carmine_Beam_Loop_C_OnWhileActiveParticleSystemDeactivate::Parameters' has a wrong offset!");

}

