#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCN_Burst_Hot_Feet_Environmental

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCN_Burst_Hot_Feet_Environmental.GCN_Burst_Hot_Feet_Environmental_C
// 0x0000 (0x0218 - 0x0218)
class UGCN_Burst_Hot_Feet_Environmental_C final : public UFortGameplayCueNotify_Burst
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCN_Burst_Hot_Feet_Environmental_C">();
	}
	static class UGCN_Burst_Hot_Feet_Environmental_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGCN_Burst_Hot_Feet_Environmental_C>();
	}
};
static_assert(alignof(UGCN_Burst_Hot_Feet_Environmental_C) == 0x000008, "Wrong alignment on UGCN_Burst_Hot_Feet_Environmental_C");
static_assert(sizeof(UGCN_Burst_Hot_Feet_Environmental_C) == 0x000218, "Wrong size on UGCN_Burst_Hot_Feet_Environmental_C");

}

