#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: M_SML_Lars_Body_Skeleton_AnimBlueprint

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "ImmediatePhysics_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass M_SML_Lars_Body_Skeleton_AnimBlueprint.M_SML_Lars_Body_Skeleton_AnimBlueprint_C
// 0x16F0 (0x1BC0 - 0x04D0)
class UM_SML_Lars_Body_Skeleton_AnimBlueprint_C final : public UCustomCharacterPartAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04D0(0x0008)(Transient, DuplicateTransient)
	uint8                                         Pad_4D8[0x8];                                      // 0x04D8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_ABBE7B9049051BD35FC06396913867D3; // 0x04E0(0x0330)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_96AE5B8B43500293DE894ABD15A077A7; // 0x0810(0x0330)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_57F8580A48FCF2889D11D5AD38EDBBB0; // 0x0B40(0x0330)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_F22264944E0128E1663A8D955C57F1C0; // 0x0E70(0x0040)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_B94146E6410326AE160256996285439C; // 0x0EB0(0x0040)()
	struct FAnimNode_Root                         AnimGraphNode_Root_30648CCA4031F2B867F3A7880FF97EEE; // 0x0EF0(0x0040)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_A0D3A35D4FDDEF364F7C0CB2BC636E9D; // 0x0F30(0x0330)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_FB6CDDC24FAA9996085270BB888E9329; // 0x1260(0x0330)()
	struct FAnimNode_CopyPoseFromMesh             AnimGraphNode_CopyPoseFromMesh_5F5AF45E4DCAF8F4BB882B97DC5046C4; // 0x1590(0x00F0)(ContainsInstancedReference)
	struct FAnimNode_RigidBody                    AnimGraphNode_RigidBody_500B74434F51B316795CD7B933386919; // 0x1680(0x0540)()

public:
	void ExecuteUbergraph_M_SML_Lars_Body_Skeleton_AnimBlueprint(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"M_SML_Lars_Body_Skeleton_AnimBlueprint_C">();
	}
	static class UM_SML_Lars_Body_Skeleton_AnimBlueprint_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UM_SML_Lars_Body_Skeleton_AnimBlueprint_C>();
	}
};
static_assert(alignof(UM_SML_Lars_Body_Skeleton_AnimBlueprint_C) == 0x000010, "Wrong alignment on UM_SML_Lars_Body_Skeleton_AnimBlueprint_C");
static_assert(sizeof(UM_SML_Lars_Body_Skeleton_AnimBlueprint_C) == 0x001BC0, "Wrong size on UM_SML_Lars_Body_Skeleton_AnimBlueprint_C");
static_assert(offsetof(UM_SML_Lars_Body_Skeleton_AnimBlueprint_C, UberGraphFrame) == 0x0004D0, "Member 'UM_SML_Lars_Body_Skeleton_AnimBlueprint_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UM_SML_Lars_Body_Skeleton_AnimBlueprint_C, AnimGraphNode_AnimDynamics_ABBE7B9049051BD35FC06396913867D3) == 0x0004E0, "Member 'UM_SML_Lars_Body_Skeleton_AnimBlueprint_C::AnimGraphNode_AnimDynamics_ABBE7B9049051BD35FC06396913867D3' has a wrong offset!");
static_assert(offsetof(UM_SML_Lars_Body_Skeleton_AnimBlueprint_C, AnimGraphNode_AnimDynamics_96AE5B8B43500293DE894ABD15A077A7) == 0x000810, "Member 'UM_SML_Lars_Body_Skeleton_AnimBlueprint_C::AnimGraphNode_AnimDynamics_96AE5B8B43500293DE894ABD15A077A7' has a wrong offset!");
static_assert(offsetof(UM_SML_Lars_Body_Skeleton_AnimBlueprint_C, AnimGraphNode_AnimDynamics_57F8580A48FCF2889D11D5AD38EDBBB0) == 0x000B40, "Member 'UM_SML_Lars_Body_Skeleton_AnimBlueprint_C::AnimGraphNode_AnimDynamics_57F8580A48FCF2889D11D5AD38EDBBB0' has a wrong offset!");
static_assert(offsetof(UM_SML_Lars_Body_Skeleton_AnimBlueprint_C, AnimGraphNode_ComponentToLocalSpace_F22264944E0128E1663A8D955C57F1C0) == 0x000E70, "Member 'UM_SML_Lars_Body_Skeleton_AnimBlueprint_C::AnimGraphNode_ComponentToLocalSpace_F22264944E0128E1663A8D955C57F1C0' has a wrong offset!");
static_assert(offsetof(UM_SML_Lars_Body_Skeleton_AnimBlueprint_C, AnimGraphNode_LocalToComponentSpace_B94146E6410326AE160256996285439C) == 0x000EB0, "Member 'UM_SML_Lars_Body_Skeleton_AnimBlueprint_C::AnimGraphNode_LocalToComponentSpace_B94146E6410326AE160256996285439C' has a wrong offset!");
static_assert(offsetof(UM_SML_Lars_Body_Skeleton_AnimBlueprint_C, AnimGraphNode_Root_30648CCA4031F2B867F3A7880FF97EEE) == 0x000EF0, "Member 'UM_SML_Lars_Body_Skeleton_AnimBlueprint_C::AnimGraphNode_Root_30648CCA4031F2B867F3A7880FF97EEE' has a wrong offset!");
static_assert(offsetof(UM_SML_Lars_Body_Skeleton_AnimBlueprint_C, AnimGraphNode_AnimDynamics_A0D3A35D4FDDEF364F7C0CB2BC636E9D) == 0x000F30, "Member 'UM_SML_Lars_Body_Skeleton_AnimBlueprint_C::AnimGraphNode_AnimDynamics_A0D3A35D4FDDEF364F7C0CB2BC636E9D' has a wrong offset!");
static_assert(offsetof(UM_SML_Lars_Body_Skeleton_AnimBlueprint_C, AnimGraphNode_AnimDynamics_FB6CDDC24FAA9996085270BB888E9329) == 0x001260, "Member 'UM_SML_Lars_Body_Skeleton_AnimBlueprint_C::AnimGraphNode_AnimDynamics_FB6CDDC24FAA9996085270BB888E9329' has a wrong offset!");
static_assert(offsetof(UM_SML_Lars_Body_Skeleton_AnimBlueprint_C, AnimGraphNode_CopyPoseFromMesh_5F5AF45E4DCAF8F4BB882B97DC5046C4) == 0x001590, "Member 'UM_SML_Lars_Body_Skeleton_AnimBlueprint_C::AnimGraphNode_CopyPoseFromMesh_5F5AF45E4DCAF8F4BB882B97DC5046C4' has a wrong offset!");
static_assert(offsetof(UM_SML_Lars_Body_Skeleton_AnimBlueprint_C, AnimGraphNode_RigidBody_500B74434F51B316795CD7B933386919) == 0x001680, "Member 'UM_SML_Lars_Body_Skeleton_AnimBlueprint_C::AnimGraphNode_RigidBody_500B74434F51B316795CD7B933386919' has a wrong offset!");

}

