#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ModalTutorialOverlay

#include "Basic.hpp"

#include "UMG_structs.hpp"


namespace SDK::Params
{

// Function ModalTutorialOverlay.ModalTutorialOverlay_C.ExecuteUbergraph_ModalTutorialOverlay
// 0x0038 (0x0038 - 0x0000)
struct ModalTutorialOverlay_C_ExecuteUbergraph_ModalTutorialOverlay final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetEndTime_ReturnValue;                   // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationAtTime_ReturnValue;          // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue;           // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCommonButton*                          K2Node_ComponentBoundEvent_Button;                 // 0x0018(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetEndTime_ReturnValue1;                  // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortUIManagerWidget_NUI*               CallFunc_GetUIManagerWidget_ReturnValue;           // 0x0028(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationAtTime_ReturnValue1;         // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ModalTutorialOverlay_C_ExecuteUbergraph_ModalTutorialOverlay) == 0x000008, "Wrong alignment on ModalTutorialOverlay_C_ExecuteUbergraph_ModalTutorialOverlay");
static_assert(sizeof(ModalTutorialOverlay_C_ExecuteUbergraph_ModalTutorialOverlay) == 0x000038, "Wrong size on ModalTutorialOverlay_C_ExecuteUbergraph_ModalTutorialOverlay");
static_assert(offsetof(ModalTutorialOverlay_C_ExecuteUbergraph_ModalTutorialOverlay, EntryPoint) == 0x000000, "Member 'ModalTutorialOverlay_C_ExecuteUbergraph_ModalTutorialOverlay::EntryPoint' has a wrong offset!");
static_assert(offsetof(ModalTutorialOverlay_C_ExecuteUbergraph_ModalTutorialOverlay, CallFunc_GetEndTime_ReturnValue) == 0x000004, "Member 'ModalTutorialOverlay_C_ExecuteUbergraph_ModalTutorialOverlay::CallFunc_GetEndTime_ReturnValue' has a wrong offset!");
static_assert(offsetof(ModalTutorialOverlay_C_ExecuteUbergraph_ModalTutorialOverlay, CallFunc_PlayAnimationAtTime_ReturnValue) == 0x000008, "Member 'ModalTutorialOverlay_C_ExecuteUbergraph_ModalTutorialOverlay::CallFunc_PlayAnimationAtTime_ReturnValue' has a wrong offset!");
static_assert(offsetof(ModalTutorialOverlay_C_ExecuteUbergraph_ModalTutorialOverlay, CallFunc_GetDynamicMaterial_ReturnValue) == 0x000010, "Member 'ModalTutorialOverlay_C_ExecuteUbergraph_ModalTutorialOverlay::CallFunc_GetDynamicMaterial_ReturnValue' has a wrong offset!");
static_assert(offsetof(ModalTutorialOverlay_C_ExecuteUbergraph_ModalTutorialOverlay, K2Node_ComponentBoundEvent_Button) == 0x000018, "Member 'ModalTutorialOverlay_C_ExecuteUbergraph_ModalTutorialOverlay::K2Node_ComponentBoundEvent_Button' has a wrong offset!");
static_assert(offsetof(ModalTutorialOverlay_C_ExecuteUbergraph_ModalTutorialOverlay, CallFunc_GetEndTime_ReturnValue1) == 0x000020, "Member 'ModalTutorialOverlay_C_ExecuteUbergraph_ModalTutorialOverlay::CallFunc_GetEndTime_ReturnValue1' has a wrong offset!");
static_assert(offsetof(ModalTutorialOverlay_C_ExecuteUbergraph_ModalTutorialOverlay, CallFunc_GetUIManagerWidget_ReturnValue) == 0x000028, "Member 'ModalTutorialOverlay_C_ExecuteUbergraph_ModalTutorialOverlay::CallFunc_GetUIManagerWidget_ReturnValue' has a wrong offset!");
static_assert(offsetof(ModalTutorialOverlay_C_ExecuteUbergraph_ModalTutorialOverlay, CallFunc_PlayAnimationAtTime_ReturnValue1) == 0x000030, "Member 'ModalTutorialOverlay_C_ExecuteUbergraph_ModalTutorialOverlay::CallFunc_PlayAnimationAtTime_ReturnValue1' has a wrong offset!");

// Function ModalTutorialOverlay.ModalTutorialOverlay_C.BndEvt__ButtonContinue_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct ModalTutorialOverlay_C_BndEvt__ButtonContinue_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature final
{
public:
	class UCommonButton*                          Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ModalTutorialOverlay_C_BndEvt__ButtonContinue_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature) == 0x000008, "Wrong alignment on ModalTutorialOverlay_C_BndEvt__ButtonContinue_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature");
static_assert(sizeof(ModalTutorialOverlay_C_BndEvt__ButtonContinue_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature) == 0x000008, "Wrong size on ModalTutorialOverlay_C_BndEvt__ButtonContinue_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature");
static_assert(offsetof(ModalTutorialOverlay_C_BndEvt__ButtonContinue_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature, Button) == 0x000000, "Member 'ModalTutorialOverlay_C_BndEvt__ButtonContinue_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature::Button' has a wrong offset!");

// Function ModalTutorialOverlay.ModalTutorialOverlay_C.Show
// 0x0070 (0x0070 - 0x0000)
struct ModalTutorialOverlay_C_Show final
{
public:
	class FText                                   inTitle;                                           // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	class FText                                   inDescription;                                     // 0x0018(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	TSoftObjectPtr<class UTexture2D>              inTexture2D;                                       // 0x0030(0x0028)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable1;                               // 0x0059(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValidSoftObjectReference_ReturnValue;   // 0x005A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable;                                // 0x005B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_TextIsEmpty_ReturnValue;                  // 0x005C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x005D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5E[0x2];                                       // 0x005E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationAtTime_ReturnValue;          // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortUINavigationManager*               CallFunc_GetUINavigationManager_ReturnValue;       // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ModalTutorialOverlay_C_Show) == 0x000008, "Wrong alignment on ModalTutorialOverlay_C_Show");
static_assert(sizeof(ModalTutorialOverlay_C_Show) == 0x000070, "Wrong size on ModalTutorialOverlay_C_Show");
static_assert(offsetof(ModalTutorialOverlay_C_Show, inTitle) == 0x000000, "Member 'ModalTutorialOverlay_C_Show::inTitle' has a wrong offset!");
static_assert(offsetof(ModalTutorialOverlay_C_Show, inDescription) == 0x000018, "Member 'ModalTutorialOverlay_C_Show::inDescription' has a wrong offset!");
static_assert(offsetof(ModalTutorialOverlay_C_Show, inTexture2D) == 0x000030, "Member 'ModalTutorialOverlay_C_Show::inTexture2D' has a wrong offset!");
static_assert(offsetof(ModalTutorialOverlay_C_Show, Temp_byte_Variable) == 0x000058, "Member 'ModalTutorialOverlay_C_Show::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(ModalTutorialOverlay_C_Show, Temp_byte_Variable1) == 0x000059, "Member 'ModalTutorialOverlay_C_Show::Temp_byte_Variable1' has a wrong offset!");
static_assert(offsetof(ModalTutorialOverlay_C_Show, CallFunc_IsValidSoftObjectReference_ReturnValue) == 0x00005A, "Member 'ModalTutorialOverlay_C_Show::CallFunc_IsValidSoftObjectReference_ReturnValue' has a wrong offset!");
static_assert(offsetof(ModalTutorialOverlay_C_Show, Temp_bool_Variable) == 0x00005B, "Member 'ModalTutorialOverlay_C_Show::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(ModalTutorialOverlay_C_Show, CallFunc_TextIsEmpty_ReturnValue) == 0x00005C, "Member 'ModalTutorialOverlay_C_Show::CallFunc_TextIsEmpty_ReturnValue' has a wrong offset!");
static_assert(offsetof(ModalTutorialOverlay_C_Show, K2Node_Select_Default) == 0x00005D, "Member 'ModalTutorialOverlay_C_Show::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(ModalTutorialOverlay_C_Show, CallFunc_PlayAnimationAtTime_ReturnValue) == 0x000060, "Member 'ModalTutorialOverlay_C_Show::CallFunc_PlayAnimationAtTime_ReturnValue' has a wrong offset!");
static_assert(offsetof(ModalTutorialOverlay_C_Show, CallFunc_GetUINavigationManager_ReturnValue) == 0x000068, "Member 'ModalTutorialOverlay_C_Show::CallFunc_GetUINavigationManager_ReturnValue' has a wrong offset!");

}

