#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MotdOverride

#include "Basic.hpp"


namespace SDK
{

// Enum MotdOverride.EMotdCloseReason
// NumValues: 0x0008
enum class EMotdCloseReason : uint8
{
	Unknown                                  = 0,
	NoMotds                                  = 1,
	NullPrm                                  = 2,
	PrmParsingFailed                         = 3,
	User                                     = 4,
	Action                                   = 5,
	DeepLink                                 = 6,
	EMotdCloseReason_MAX                     = 7,
};

}

