#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OnlineSubsystemMcp

#include "Basic.hpp"

#include "LinkId_structs.hpp"


namespace SDK
{

// Enum OnlineSubsystemMcp.ESocialCommsPermission
// NumValues: 0x0005
enum class ESocialCommsPermission : uint8
{
	Nobody                                   = 0,
	FriendsOnly                              = 1,
	FriendsAndTeammates                      = 2,
	Everybody                                = 3,
	ESocialCommsPermission_MAX               = 4,
};

// Enum OnlineSubsystemMcp.ESocialProfilePrivacySettingLevel
// NumValues: 0x0004
enum class ESocialProfilePrivacySettingLevel : uint8
{
	Public                                   = 0,
	FriendsOnly                              = 1,
	Private                                  = 2,
	ESocialProfilePrivacySettingLevel_MAX    = 3,
};

// Enum OnlineSubsystemMcp.ESocialProfilePrivacySettingBadges
// NumValues: 0x0003
enum class ESocialProfilePrivacySettingBadges : uint8
{
	FriendsOnly                              = 0,
	Private                                  = 1,
	ESocialProfilePrivacySettingBadges_MAX   = 2,
};

// Enum OnlineSubsystemMcp.EMutualFriendsPrivacyPolicy
// NumValues: 0x0005
enum class EMutualFriendsPrivacyPolicy : uint8
{
	All                                      = 0,
	Friends                                  = 1,
	None                                     = 2,
	InvalidOrMax                             = 3,
	EMutualFriendsPrivacyPolicy_MAX          = 4,
};

// Enum OnlineSubsystemMcp.ESupervisedSettingsRestrictiveOrder
// NumValues: 0x0008
enum class ESupervisedSettingsRestrictiveOrder : uint8
{
	FirstRestrictive                         = 0,
	FirstPermissive                          = 1,
	LowRestrictive                           = 2,
	LowPermissive                            = 3,
	FalseRestrictive                         = 4,
	FalsePermissive                          = 5,
	None                                     = 6,
	ESupervisedSettingsRestrictiveOrder_MAX  = 7,
};

// Enum OnlineSubsystemMcp.ESupervisedSettingsValueType
// NumValues: 0x0005
enum class ESupervisedSettingsValueType : uint8
{
	Boolean                                  = 0,
	Numeric                                  = 1,
	Option                                   = 2,
	None                                     = 3,
	ESupervisedSettingsValueType_MAX         = 4,
};

// ScriptStruct OnlineSubsystemMcp.JsonToxicityEvaluationRequest
// 0x0010 (0x0010 - 0x0000)
struct FJsonToxicityEvaluationRequest final
{
public:
	class FString                                 Name;                                              // 0x0000(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FJsonToxicityEvaluationRequest) == 0x000008, "Wrong alignment on FJsonToxicityEvaluationRequest");
static_assert(sizeof(FJsonToxicityEvaluationRequest) == 0x000010, "Wrong size on FJsonToxicityEvaluationRequest");

// ScriptStruct OnlineSubsystemMcp.OnlineIARCLocaleMapping
// 0x0020 (0x0020 - 0x0000)
struct FOnlineIARCLocaleMapping final
{
public:
	class FString                                 LanguageId;                                        // 0x0000(0x0010)(ZeroConstructor, Config, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 IARCLocaleId;                                      // 0x0010(0x0010)(ZeroConstructor, Config, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FOnlineIARCLocaleMapping) == 0x000008, "Wrong alignment on FOnlineIARCLocaleMapping");
static_assert(sizeof(FOnlineIARCLocaleMapping) == 0x000020, "Wrong size on FOnlineIARCLocaleMapping");

// ScriptStruct OnlineSubsystemMcp.OnlineDiscoveryModeSetDef
// 0x0038 (0x0038 - 0x0000)
struct FOnlineDiscoveryModeSetDef final
{
public:
	struct FOnlineLinkId                          ModeSetId;                                         // 0x0000(0x0018)(HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 SubModeLinkType;                                   // 0x0018(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FOnlineLinkId>                  SubModeLinkIds;                                    // 0x0028(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
};
static_assert(alignof(FOnlineDiscoveryModeSetDef) == 0x000008, "Wrong alignment on FOnlineDiscoveryModeSetDef");
static_assert(sizeof(FOnlineDiscoveryModeSetDef) == 0x000038, "Wrong size on FOnlineDiscoveryModeSetDef");

// ScriptStruct OnlineSubsystemMcp.JsonToxicityEvaluationResponse
// 0x0001 (0x0001 - 0x0000)
struct FJsonToxicityEvaluationResponse final
{
public:
	bool                                          Toxic;                                             // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FJsonToxicityEvaluationResponse) == 0x000001, "Wrong alignment on FJsonToxicityEvaluationResponse");
static_assert(sizeof(FJsonToxicityEvaluationResponse) == 0x000001, "Wrong size on FJsonToxicityEvaluationResponse");

// ScriptStruct OnlineSubsystemMcp.OnlineDiscoverySurfaceDevelopmentLinkCodes
// 0x0018 (0x0018 - 0x0000)
struct FOnlineDiscoverySurfaceDevelopmentLinkCodes final
{
public:
	class FName                                   SurfaceName;                                       // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FString>                         DevelopmentLinkCodes;                              // 0x0008(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
};
static_assert(alignof(FOnlineDiscoverySurfaceDevelopmentLinkCodes) == 0x000008, "Wrong alignment on FOnlineDiscoverySurfaceDevelopmentLinkCodes");
static_assert(sizeof(FOnlineDiscoverySurfaceDevelopmentLinkCodes) == 0x000018, "Wrong size on FOnlineDiscoverySurfaceDevelopmentLinkCodes");

// ScriptStruct OnlineSubsystemMcp.OnlineISORegionInfo
// 0x0030 (0x0030 - 0x0000)
struct FOnlineISORegionInfo final
{
public:
	class FText                                   DisplayName;                                       // 0x0000(0x0010)(Config, NativeAccessSpecifierPublic)
	class FString                                 RegionId;                                          // 0x0010(0x0010)(ZeroConstructor, Config, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 BackendId;                                         // 0x0020(0x0010)(ZeroConstructor, Config, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FOnlineISORegionInfo) == 0x000008, "Wrong alignment on FOnlineISORegionInfo");
static_assert(sizeof(FOnlineISORegionInfo) == 0x000030, "Wrong size on FOnlineISORegionInfo");

// ScriptStruct OnlineSubsystemMcp.OnlineISOLanguageInfo
// 0x0030 (0x0030 - 0x0000)
struct FOnlineISOLanguageInfo final
{
public:
	class FText                                   DisplayName;                                       // 0x0000(0x0010)(Config, NativeAccessSpecifierPublic)
	class FString                                 LanguageId;                                        // 0x0010(0x0010)(ZeroConstructor, Config, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 BackendId;                                         // 0x0020(0x0010)(ZeroConstructor, Config, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FOnlineISOLanguageInfo) == 0x000008, "Wrong alignment on FOnlineISOLanguageInfo");
static_assert(sizeof(FOnlineISOLanguageInfo) == 0x000030, "Wrong size on FOnlineISOLanguageInfo");

// ScriptStruct OnlineSubsystemMcp.JsonToxicityEvaluationRequestLegacy
// 0x0010 (0x0010 - 0x0000)
struct FJsonToxicityEvaluationRequestLegacy final
{
public:
	class FString                                 Text;                                              // 0x0000(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FJsonToxicityEvaluationRequestLegacy) == 0x000008, "Wrong alignment on FJsonToxicityEvaluationRequestLegacy");
static_assert(sizeof(FJsonToxicityEvaluationRequestLegacy) == 0x000010, "Wrong size on FJsonToxicityEvaluationRequestLegacy");

// ScriptStruct OnlineSubsystemMcp.JsonToxicityBulkEvaluationRequestLegacy
// 0x0010 (0x0010 - 0x0000)
struct FJsonToxicityBulkEvaluationRequestLegacy final
{
public:
	TArray<class FString>                         Texts;                                             // 0x0000(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
};
static_assert(alignof(FJsonToxicityBulkEvaluationRequestLegacy) == 0x000008, "Wrong alignment on FJsonToxicityBulkEvaluationRequestLegacy");
static_assert(sizeof(FJsonToxicityBulkEvaluationRequestLegacy) == 0x000010, "Wrong size on FJsonToxicityBulkEvaluationRequestLegacy");

// ScriptStruct OnlineSubsystemMcp.JsonToxicityBulkEvaluationRequest
// 0x0010 (0x0010 - 0x0000)
struct FJsonToxicityBulkEvaluationRequest final
{
public:
	TArray<class FString>                         Names;                                             // 0x0000(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
};
static_assert(alignof(FJsonToxicityBulkEvaluationRequest) == 0x000008, "Wrong alignment on FJsonToxicityBulkEvaluationRequest");
static_assert(sizeof(FJsonToxicityBulkEvaluationRequest) == 0x000010, "Wrong size on FJsonToxicityBulkEvaluationRequest");

// ScriptStruct OnlineSubsystemMcp.JsonToxicityBulkEvaluationResponse
// 0x0010 (0x0010 - 0x0000)
struct FJsonToxicityBulkEvaluationResponse final
{
public:
	TArray<bool>                                  IsToxic;                                           // 0x0000(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
};
static_assert(alignof(FJsonToxicityBulkEvaluationResponse) == 0x000008, "Wrong alignment on FJsonToxicityBulkEvaluationResponse");
static_assert(sizeof(FJsonToxicityBulkEvaluationResponse) == 0x000010, "Wrong size on FJsonToxicityBulkEvaluationResponse");

}

