#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlayedBeforeSelect

#include "Basic.hpp"


namespace SDK::Params
{

// Function PlayedBeforeSelect.PlayedBeforeSelect_C.ExecuteUbergraph_PlayedBeforeSelect
// 0x0004 (0x0004 - 0x0000)
struct PlayedBeforeSelect_C_ExecuteUbergraph_PlayedBeforeSelect final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PlayedBeforeSelect_C_ExecuteUbergraph_PlayedBeforeSelect) == 0x000004, "Wrong alignment on PlayedBeforeSelect_C_ExecuteUbergraph_PlayedBeforeSelect");
static_assert(sizeof(PlayedBeforeSelect_C_ExecuteUbergraph_PlayedBeforeSelect) == 0x000004, "Wrong size on PlayedBeforeSelect_C_ExecuteUbergraph_PlayedBeforeSelect");
static_assert(offsetof(PlayedBeforeSelect_C_ExecuteUbergraph_PlayedBeforeSelect, EntryPoint) == 0x000000, "Member 'PlayedBeforeSelect_C_ExecuteUbergraph_PlayedBeforeSelect::EntryPoint' has a wrong offset!");

}

