#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RefundTicket

#include "Basic.hpp"


namespace SDK::Params
{

// Function RefundTicket.RefundTicket_C.ExecuteUbergraph_RefundTicket
// 0x0008 (0x0008 - 0x0000)
struct RefundTicket_C_ExecuteUbergraph_RefundTicket final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_isPending;                      // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(RefundTicket_C_ExecuteUbergraph_RefundTicket) == 0x000004, "Wrong alignment on RefundTicket_C_ExecuteUbergraph_RefundTicket");
static_assert(sizeof(RefundTicket_C_ExecuteUbergraph_RefundTicket) == 0x000008, "Wrong size on RefundTicket_C_ExecuteUbergraph_RefundTicket");
static_assert(offsetof(RefundTicket_C_ExecuteUbergraph_RefundTicket, EntryPoint) == 0x000000, "Member 'RefundTicket_C_ExecuteUbergraph_RefundTicket::EntryPoint' has a wrong offset!");
static_assert(offsetof(RefundTicket_C_ExecuteUbergraph_RefundTicket, K2Node_CustomEvent_isPending) == 0x000004, "Member 'RefundTicket_C_ExecuteUbergraph_RefundTicket::K2Node_CustomEvent_isPending' has a wrong offset!");

// Function RefundTicket.RefundTicket_C.PendingEvent
// 0x0001 (0x0001 - 0x0000)
struct RefundTicket_C_PendingEvent final
{
public:
	bool                                          IsPending;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(RefundTicket_C_PendingEvent) == 0x000001, "Wrong alignment on RefundTicket_C_PendingEvent");
static_assert(sizeof(RefundTicket_C_PendingEvent) == 0x000001, "Wrong size on RefundTicket_C_PendingEvent");
static_assert(offsetof(RefundTicket_C_PendingEvent, IsPending) == 0x000000, "Member 'RefundTicket_C_PendingEvent::IsPending' has a wrong offset!");

}

