#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SidebarPanelYourProfile

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"
#include "CommonInput_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass SidebarPanelYourProfile.SidebarPanelYourProfile_C
// 0x0038 (0x0580 - 0x0548)
class USidebarPanelYourProfile_C final : public UFortSidebarPanelYourProfile
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0548(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       OnContentLoaded;                                   // 0x0550(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UCommonBorder*                          Border_PresenceRegion;                             // 0x0558(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                ContainerTouch;                                    // 0x0560(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UScrollBox*                             ScrollBox_Details;                                 // 0x0568(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USidebarProfileLoading_C*               SidebarProfileLoading;                             // 0x0570(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           VBox_Details;                                      // 0x0578(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ChangeParentOnTouch(bool IsTouch);
	void ExecuteUbergraph_SidebarPanelYourProfile(int32 EntryPoint);
	void OnFinishedProfileLoading();
	void OnInitialized();
	void OnInputMethodChanged(ECommonInputType NewInputType);
	void OnStartProfileLoading();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SidebarPanelYourProfile_C">();
	}
	static class USidebarPanelYourProfile_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USidebarPanelYourProfile_C>();
	}
};
static_assert(alignof(USidebarPanelYourProfile_C) == 0x000008, "Wrong alignment on USidebarPanelYourProfile_C");
static_assert(sizeof(USidebarPanelYourProfile_C) == 0x000580, "Wrong size on USidebarPanelYourProfile_C");

}

