#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SquadTilePopupMenu

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_structs.hpp"
#include "FortniteUI_classes.hpp"
#include "SquadTilePopupMenuButtons_structs.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass SquadTilePopupMenu.SquadTilePopupMenu_C
// 0x00C8 (0x0400 - 0x0338)
class USquadTilePopupMenu_C final : public UFortSquadSlotSelectorPopupMenu
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0338(0x0008)(Transient, DuplicateTransient)
	class UWidgetAnimation*                       FadeOut_;                                          // 0x0340(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       FadeIn;                                            // 0x0348(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UIconTextButton_C*                      CancelButton;                                      // 0x0350(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 CheckMark;                                         // 0x0358(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UIconTextButton_C*                      EditSlotButton;                                    // 0x0360(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UIconTextButton_C*                      InspectButton;                                     // 0x0368(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           MainButtonVerticalBox;                             // 0x0370(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UIconTextButton_C*                      ToggleAutoSlotButton;                              // 0x0378(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UIconTextButton_C*                      ToggleFavoriteButton;                              // 0x0380(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UIconTextButton_C*                      ViewAllButton;                                     // 0x0388(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               MID_CheckBox;                                      // 0x0390(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CollectionBookItemSlotId;                          // 0x0398(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CanSlotItemInCollectionBook;                       // 0x03A0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3A1[0x7];                                      // 0x03A1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CollectionBookConfirmationDialogTitle;             // 0x03A8(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                   CollectionBookConfirmationDialogMessage;           // 0x03C0(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FDataTableRowHandle                    SlotItemInCollectionBookAction;                    // 0x03D8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FDataTableRowHandle                    BackAction;                                        // 0x03E8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FFortDialogExternalLatentActionHandle  CollectionBookLatentDialogHandle;                  // 0x03F8(0x0004)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	ESquadTilePopupMenuButtons                    SelectedButton;                                    // 0x03FC(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_SquadTilePopupMenu(int32 EntryPoint);
	void BndEvt__ToggleFavoriteButton_K2Node_ComponentBoundEvent_210_CommonButtonClicked__DelegateSignature(class UCommonButton* Button);
	void BndEvt__ToggleAutoSlotButton_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature(class UCommonButton* Button);
	void WidgetAnimationEvt_FadeIn_K2Node_WidgetAnimationEvent_0();
	void BndEvt__AddToCollectionButton_K2Node_ComponentBoundEvent_230_CommonButtonClicked__DelegateSignature(class UCommonButton* Button);
	void OnDeactivated();
	void Initialize();
	void HandlePostDifferentContextProviderSet();
	void BndEvt__CancelButton_K2Node_ComponentBoundEvent_273_CommonButtonClicked__DelegateSignature(class UCommonButton* Button);
	void OnBeginIntro();
	void OnBeginOutro();
	void BndEvt__ButtonAddToCB_K2Node_ComponentBoundEvent_10_CommonButtonClicked__DelegateSignature(class UCommonButton* Button);
	void Construct();
	void BndEvt__CompareButton_K2Node_ComponentBoundEvent_81_CommonButtonClicked__DelegateSignature(class UCommonButton* Button);
	void OnActivated();
	void DialogResult_8376CF1645705E213E885D910612B437(EFortDialogResult Result, class FName ResultName);
	void DialogResult_B23277984094C4C262BC19A4495FDFD5(EFortDialogResult Result, class FName ResultName);
	void SetViewAllText();
	void GetItemInSlot(class UFortItem** Item);
	void UpdateAutoFillButtonText();
	void CheckLevelUpQuestStatus(bool* RelevantQuestFound);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SquadTilePopupMenu_C">();
	}
	static class USquadTilePopupMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USquadTilePopupMenu_C>();
	}
};
static_assert(alignof(USquadTilePopupMenu_C) == 0x000008, "Wrong alignment on USquadTilePopupMenu_C");
static_assert(sizeof(USquadTilePopupMenu_C) == 0x000400, "Wrong size on USquadTilePopupMenu_C");
static_assert(offsetof(USquadTilePopupMenu_C, UberGraphFrame) == 0x000338, "Member 'USquadTilePopupMenu_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(USquadTilePopupMenu_C, FadeOut_) == 0x000340, "Member 'USquadTilePopupMenu_C::FadeOut_' has a wrong offset!");
static_assert(offsetof(USquadTilePopupMenu_C, FadeIn) == 0x000348, "Member 'USquadTilePopupMenu_C::FadeIn' has a wrong offset!");
static_assert(offsetof(USquadTilePopupMenu_C, CancelButton) == 0x000350, "Member 'USquadTilePopupMenu_C::CancelButton' has a wrong offset!");
static_assert(offsetof(USquadTilePopupMenu_C, CheckMark) == 0x000358, "Member 'USquadTilePopupMenu_C::CheckMark' has a wrong offset!");
static_assert(offsetof(USquadTilePopupMenu_C, EditSlotButton) == 0x000360, "Member 'USquadTilePopupMenu_C::EditSlotButton' has a wrong offset!");
static_assert(offsetof(USquadTilePopupMenu_C, InspectButton) == 0x000368, "Member 'USquadTilePopupMenu_C::InspectButton' has a wrong offset!");
static_assert(offsetof(USquadTilePopupMenu_C, MainButtonVerticalBox) == 0x000370, "Member 'USquadTilePopupMenu_C::MainButtonVerticalBox' has a wrong offset!");
static_assert(offsetof(USquadTilePopupMenu_C, ToggleAutoSlotButton) == 0x000378, "Member 'USquadTilePopupMenu_C::ToggleAutoSlotButton' has a wrong offset!");
static_assert(offsetof(USquadTilePopupMenu_C, ToggleFavoriteButton) == 0x000380, "Member 'USquadTilePopupMenu_C::ToggleFavoriteButton' has a wrong offset!");
static_assert(offsetof(USquadTilePopupMenu_C, ViewAllButton) == 0x000388, "Member 'USquadTilePopupMenu_C::ViewAllButton' has a wrong offset!");
static_assert(offsetof(USquadTilePopupMenu_C, MID_CheckBox) == 0x000390, "Member 'USquadTilePopupMenu_C::MID_CheckBox' has a wrong offset!");
static_assert(offsetof(USquadTilePopupMenu_C, CollectionBookItemSlotId) == 0x000398, "Member 'USquadTilePopupMenu_C::CollectionBookItemSlotId' has a wrong offset!");
static_assert(offsetof(USquadTilePopupMenu_C, CanSlotItemInCollectionBook) == 0x0003A0, "Member 'USquadTilePopupMenu_C::CanSlotItemInCollectionBook' has a wrong offset!");
static_assert(offsetof(USquadTilePopupMenu_C, CollectionBookConfirmationDialogTitle) == 0x0003A8, "Member 'USquadTilePopupMenu_C::CollectionBookConfirmationDialogTitle' has a wrong offset!");
static_assert(offsetof(USquadTilePopupMenu_C, CollectionBookConfirmationDialogMessage) == 0x0003C0, "Member 'USquadTilePopupMenu_C::CollectionBookConfirmationDialogMessage' has a wrong offset!");
static_assert(offsetof(USquadTilePopupMenu_C, SlotItemInCollectionBookAction) == 0x0003D8, "Member 'USquadTilePopupMenu_C::SlotItemInCollectionBookAction' has a wrong offset!");
static_assert(offsetof(USquadTilePopupMenu_C, BackAction) == 0x0003E8, "Member 'USquadTilePopupMenu_C::BackAction' has a wrong offset!");
static_assert(offsetof(USquadTilePopupMenu_C, CollectionBookLatentDialogHandle) == 0x0003F8, "Member 'USquadTilePopupMenu_C::CollectionBookLatentDialogHandle' has a wrong offset!");
static_assert(offsetof(USquadTilePopupMenu_C, SelectedButton) == 0x0003FC, "Member 'USquadTilePopupMenu_C::SelectedButton' has a wrong offset!");

}

