#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TouchMoveStick

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass TouchMoveStick.TouchMoveStick_C
// 0x0030 (0x03A8 - 0x0378)
class UTouchMoveStick_C final : public UFortTouchMoveStick
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0378(0x0008)(Transient, DuplicateTransient)
	class UImage*                                 Image_Move_Thumb;                                  // 0x0380(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Move_Thumb_BG;                               // 0x0388(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	float                                         ThumbstickMoveScale;                               // 0x0390(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         AlphaInterpSpeed;                                  // 0x0394(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         TargetOpacity;                                     // 0x0398(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         TouchedOpacity;                                    // 0x039C(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         UntouchedOpacity;                                  // 0x03A0(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_TouchMoveStick(int32 EntryPoint);
	void HandleTouchEnded();
	void HandleTouchStarted();
	void SetMovementLockStatus(bool MovementIsLocked);
	void SetStickPosition(const struct FVector2D& NewPosition);
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	void Construct();
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TouchMoveStick_C">();
	}
	static class UTouchMoveStick_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTouchMoveStick_C>();
	}
};
static_assert(alignof(UTouchMoveStick_C) == 0x000008, "Wrong alignment on UTouchMoveStick_C");
static_assert(sizeof(UTouchMoveStick_C) == 0x0003A8, "Wrong size on UTouchMoveStick_C");
static_assert(offsetof(UTouchMoveStick_C, UberGraphFrame) == 0x000378, "Member 'UTouchMoveStick_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UTouchMoveStick_C, Image_Move_Thumb) == 0x000380, "Member 'UTouchMoveStick_C::Image_Move_Thumb' has a wrong offset!");
static_assert(offsetof(UTouchMoveStick_C, Image_Move_Thumb_BG) == 0x000388, "Member 'UTouchMoveStick_C::Image_Move_Thumb_BG' has a wrong offset!");
static_assert(offsetof(UTouchMoveStick_C, ThumbstickMoveScale) == 0x000390, "Member 'UTouchMoveStick_C::ThumbstickMoveScale' has a wrong offset!");
static_assert(offsetof(UTouchMoveStick_C, AlphaInterpSpeed) == 0x000394, "Member 'UTouchMoveStick_C::AlphaInterpSpeed' has a wrong offset!");
static_assert(offsetof(UTouchMoveStick_C, TargetOpacity) == 0x000398, "Member 'UTouchMoveStick_C::TargetOpacity' has a wrong offset!");
static_assert(offsetof(UTouchMoveStick_C, TouchedOpacity) == 0x00039C, "Member 'UTouchMoveStick_C::TouchedOpacity' has a wrong offset!");
static_assert(offsetof(UTouchMoveStick_C, UntouchedOpacity) == 0x0003A0, "Member 'UTouchMoveStick_C::UntouchedOpacity' has a wrong offset!");

}

