#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UIKit_Block_InputField_Background

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function WBP_UIKit_Block_InputField_Background.WBP_UIKit_Block_InputField_Background_C.ExecuteUbergraph_WBP_UIKit_Block_InputField_Background
// 0x000C (0x000C - 0x0000)
struct WBP_UIKit_Block_InputField_Background_C_ExecuteUbergraph_WBP_UIKit_Block_InputField_Background final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetIsSelected_IsSelected;                 // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetIsSelectable_IsSelectable;             // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetIsSelectable_IsSelectable_1;           // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetIsSelectable_IsSelectable_2;           // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetIsSelectable_IsSelectable_3;           // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_UIKit_Block_InputField_Background_C_ExecuteUbergraph_WBP_UIKit_Block_InputField_Background) == 0x000004, "Wrong alignment on WBP_UIKit_Block_InputField_Background_C_ExecuteUbergraph_WBP_UIKit_Block_InputField_Background");
static_assert(sizeof(WBP_UIKit_Block_InputField_Background_C_ExecuteUbergraph_WBP_UIKit_Block_InputField_Background) == 0x00000C, "Wrong size on WBP_UIKit_Block_InputField_Background_C_ExecuteUbergraph_WBP_UIKit_Block_InputField_Background");

// Function WBP_UIKit_Block_InputField_Background.WBP_UIKit_Block_InputField_Background_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_UIKit_Block_InputField_Background_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_UIKit_Block_InputField_Background_C_PreConstruct) == 0x000001, "Wrong alignment on WBP_UIKit_Block_InputField_Background_C_PreConstruct");
static_assert(sizeof(WBP_UIKit_Block_InputField_Background_C_PreConstruct) == 0x000001, "Wrong size on WBP_UIKit_Block_InputField_Background_C_PreConstruct");

// Function WBP_UIKit_Block_InputField_Background.WBP_UIKit_Block_InputField_Background_C.SetBackgroundBrush
// 0x00D0 (0x00D0 - 0x0000)
struct WBP_UIKit_Block_InputField_Background_C_SetBackgroundBrush final
{
public:
	struct FSlateBrush                            InBrush;                                           // 0x0000(0x00C0)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue;           // 0x00C0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_UIKit_Block_InputField_Background_C_SetBackgroundBrush) == 0x000010, "Wrong alignment on WBP_UIKit_Block_InputField_Background_C_SetBackgroundBrush");
static_assert(sizeof(WBP_UIKit_Block_InputField_Background_C_SetBackgroundBrush) == 0x0000D0, "Wrong size on WBP_UIKit_Block_InputField_Background_C_SetBackgroundBrush");

// Function WBP_UIKit_Block_InputField_Background.WBP_UIKit_Block_InputField_Background_C.SetBackgroundMaterial
// 0x0010 (0x0010 - 0x0000)
struct WBP_UIKit_Block_InputField_Background_C_SetBackgroundMaterial final
{
public:
	const class UMaterialInstance*                Material_Instance;                                 // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue;           // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_UIKit_Block_InputField_Background_C_SetBackgroundMaterial) == 0x000008, "Wrong alignment on WBP_UIKit_Block_InputField_Background_C_SetBackgroundMaterial");
static_assert(sizeof(WBP_UIKit_Block_InputField_Background_C_SetBackgroundMaterial) == 0x000010, "Wrong size on WBP_UIKit_Block_InputField_Background_C_SetBackgroundMaterial");

// Function WBP_UIKit_Block_InputField_Background.WBP_UIKit_Block_InputField_Background_C.SetCornerRadius
// 0x0058 (0x0058 - 0x0000)
struct WBP_UIKit_Block_InputField_Background_C_SetCornerRadius final
{
public:
	bool                                          Radius_in_Pixels;                                  // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        TopLeft;                                           // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        TopRight;                                          // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        BottomRight;                                       // 0x0018(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        BottomLeft;                                        // 0x0020(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           K2Node_MakeStruct_LinearColor;                     // 0x0028(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Conv_BoolToDouble_ReturnValue;            // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_MakeStruct_R_ImplicitCast;                  // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_MakeStruct_B_ImplicitCast;                  // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_MakeStruct_A_ImplicitCast;                  // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_MakeStruct_G_ImplicitCast;                  // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetScalarParameterValue_Value_ImplicitCast; // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_UIKit_Block_InputField_Background_C_SetCornerRadius) == 0x000008, "Wrong alignment on WBP_UIKit_Block_InputField_Background_C_SetCornerRadius");
static_assert(sizeof(WBP_UIKit_Block_InputField_Background_C_SetCornerRadius) == 0x000058, "Wrong size on WBP_UIKit_Block_InputField_Background_C_SetCornerRadius");

}

