#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UIKit_Block_Base

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_UIKit_Block_Base.WBP_UIKit_Block_Base_C
// 0x0008 (0x0300 - 0x02F8)
class UWBP_UIKit_Block_Base_C : public UUIKitBlock
{
public:
	bool                                          IsSelectable;                                      // 0x02F8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsSelected;                                        // 0x02F9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsLocked;                                          // 0x02FA(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void GetIsLocked(bool* IsLocked_0);
	void GetIsSelectable(bool* IsSelectable_0);
	void GetIsSelected(bool* IsSelected_0);
	void SetBlockVisibility(bool Visible);
	void SetIsLocked(bool Is_Locked);
	void SetIsSelectable(bool Is_Selectable);
	void SetIsSelected(bool IsSelected_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_UIKit_Block_Base_C">();
	}
	static class UWBP_UIKit_Block_Base_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_UIKit_Block_Base_C>();
	}
};
static_assert(alignof(UWBP_UIKit_Block_Base_C) == 0x000008, "Wrong alignment on UWBP_UIKit_Block_Base_C");
static_assert(sizeof(UWBP_UIKit_Block_Base_C) == 0x000300, "Wrong size on UWBP_UIKit_Block_Base_C");

}

