#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ContentGate_RatingCardButton

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"
#include "FortniteGame_structs.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_ContentGate_RatingCardButton.WBP_ContentGate_RatingCardButton_C
// 0x0040 (0x1500 - 0x14C0)
class UWBP_ContentGate_RatingCardButton_C final : public UUIKitModularButton
{
public:
	uint8                                         Pad_14B8[0x8];                                     // 0x14B8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x14C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_UIKit_Block_Outline_C*             Block_Outline;                                     // 0x14C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Divider_2;                                   // 0x14D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_RatingIcon;                                  // 0x14D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_ContentDescriptor;                            // 0x14E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_InteractionDescriptor;                        // 0x14E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_Rating;                                       // 0x14F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UFortGameActivity*                      CachedGameActivity;                                // 0x14F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void BP_OnClicked();
	void BP_OnHovered();
	void BP_OnUnhovered();
	void Construct();
	void ExecuteUbergraph_WBP_ContentGate_RatingCardButton(int32 EntryPoint);
	void GetTextFromDescriptorArray(TArray<class FText>& Descriptors, class FText* Text);
	void PreConstruct(bool IsDesignTime);
	void ShowGameRatingInfo(class UFortGameActivity* GameActivity);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_ContentGate_RatingCardButton_C">();
	}
	static class UWBP_ContentGate_RatingCardButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ContentGate_RatingCardButton_C>();
	}
};
static_assert(alignof(UWBP_ContentGate_RatingCardButton_C) == 0x000010, "Wrong alignment on UWBP_ContentGate_RatingCardButton_C");
static_assert(sizeof(UWBP_ContentGate_RatingCardButton_C) == 0x001500, "Wrong size on UWBP_ContentGate_RatingCardButton_C");

}

