#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SubCategoryCarousel_Button

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_SubCategoryCarousel_Button.WBP_SubCategoryCarousel_Button_C.SetFortLockerCategoryItemVM
// 0x0028 (0x0028 - 0x0000)
struct WBP_SubCategoryCarousel_Button_C_SetFortLockerCategoryItemVM final
{
public:
	class UFortLockerCategoryItemVM*              ViewModel;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UMVVMView*                              CallFunc_GetExtension_ReturnValue;                 // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class INotifyFieldValueChanged> CallFunc_SetViewModel_ViewModel_CastInput;         // 0x0010(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          CallFunc_SetViewModel_ReturnValue;                 // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_SubCategoryCarousel_Button_C_SetFortLockerCategoryItemVM) == 0x000008, "Wrong alignment on WBP_SubCategoryCarousel_Button_C_SetFortLockerCategoryItemVM");
static_assert(sizeof(WBP_SubCategoryCarousel_Button_C_SetFortLockerCategoryItemVM) == 0x000028, "Wrong size on WBP_SubCategoryCarousel_Button_C_SetFortLockerCategoryItemVM");

// Function WBP_SubCategoryCarousel_Button.WBP_SubCategoryCarousel_Button_C.UpdateState
// 0x0001 (0x0001 - 0x0000)
struct WBP_SubCategoryCarousel_Button_C_UpdateState final
{
public:
	bool                                          HasNewItems;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_SubCategoryCarousel_Button_C_UpdateState) == 0x000001, "Wrong alignment on WBP_SubCategoryCarousel_Button_C_UpdateState");
static_assert(sizeof(WBP_SubCategoryCarousel_Button_C_UpdateState) == 0x000001, "Wrong size on WBP_SubCategoryCarousel_Button_C_UpdateState");

}

