#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Juno_WorldSettings_BaseSetting

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "UMG_structs.hpp"


namespace SDK::Params
{

// Function WBP_Juno_WorldSettings_BaseSetting.WBP_Juno_WorldSettings_BaseSetting_C.ExecuteUbergraph_WBP_Juno_WorldSettings_BaseSetting
// 0x0008 (0x0008 - 0x0000)
struct WBP_Juno_WorldSettings_BaseSetting_C_ExecuteUbergraph_WBP_Juno_WorldSettings_BaseSetting final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Juno_WorldSettings_BaseSetting_C_ExecuteUbergraph_WBP_Juno_WorldSettings_BaseSetting) == 0x000004, "Wrong alignment on WBP_Juno_WorldSettings_BaseSetting_C_ExecuteUbergraph_WBP_Juno_WorldSettings_BaseSetting");
static_assert(sizeof(WBP_Juno_WorldSettings_BaseSetting_C_ExecuteUbergraph_WBP_Juno_WorldSettings_BaseSetting) == 0x000008, "Wrong size on WBP_Juno_WorldSettings_BaseSetting_C_ExecuteUbergraph_WBP_Juno_WorldSettings_BaseSetting");

// Function WBP_Juno_WorldSettings_BaseSetting.WBP_Juno_WorldSettings_BaseSetting_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_Juno_WorldSettings_BaseSetting_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Juno_WorldSettings_BaseSetting_C_PreConstruct) == 0x000001, "Wrong alignment on WBP_Juno_WorldSettings_BaseSetting_C_PreConstruct");
static_assert(sizeof(WBP_Juno_WorldSettings_BaseSetting_C_PreConstruct) == 0x000001, "Wrong size on WBP_Juno_WorldSettings_BaseSetting_C_PreConstruct");

// Function WBP_Juno_WorldSettings_BaseSetting.WBP_Juno_WorldSettings_BaseSetting_C.SelectedOptionChangedEvent__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_Juno_WorldSettings_BaseSetting_C_SelectedOptionChangedEvent__DelegateSignature final
{
public:
	class UJunoWorldSettingViewModel*             WorldSettingViewModel;                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Juno_WorldSettings_BaseSetting_C_SelectedOptionChangedEvent__DelegateSignature) == 0x000008, "Wrong alignment on WBP_Juno_WorldSettings_BaseSetting_C_SelectedOptionChangedEvent__DelegateSignature");
static_assert(sizeof(WBP_Juno_WorldSettings_BaseSetting_C_SelectedOptionChangedEvent__DelegateSignature) == 0x000008, "Wrong size on WBP_Juno_WorldSettings_BaseSetting_C_SelectedOptionChangedEvent__DelegateSignature");

// Function WBP_Juno_WorldSettings_BaseSetting.WBP_Juno_WorldSettings_BaseSetting_C.SetContentSizeRule
// 0x0048 (0x0048 - 0x0000)
struct WBP_Juno_WorldSettings_BaseSetting_C_SetContentSizeRule final
{
public:
	bool                                          NewShouldExpandRightContent;                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2[0x2];                                        // 0x0002(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateChildSize                        K2Node_MakeStruct_SlateChildSize;                  // 0x0004(0x0008)(NoDestructor)
	struct FSlateChildSize                        K2Node_MakeStruct_SlateChildSize_1;                // 0x000C(0x0008)(NoDestructor)
	struct FSlateChildSize                        K2Node_MakeStruct_SlateChildSize_2;                // 0x0014(0x0008)(NoDestructor)
	struct FSlateChildSize                        K2Node_MakeStruct_SlateChildSize_3;                // 0x001C(0x0008)(NoDestructor)
	bool                                          Temp_bool_Variable_1;                              // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_25[0x3];                                       // 0x0025(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UHorizontalBoxSlot*                     CallFunc_SlotAsHorizontalBoxSlot_ReturnValue;      // 0x0028(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FSlateChildSize                        K2Node_Select_Default;                             // 0x0030(0x0008)(NoDestructor)
	class UHorizontalBoxSlot*                     CallFunc_SlotAsHorizontalBoxSlot_ReturnValue_1;    // 0x0038(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FSlateChildSize                        K2Node_Select_Default_1;                           // 0x0040(0x0008)(NoDestructor)
};
static_assert(alignof(WBP_Juno_WorldSettings_BaseSetting_C_SetContentSizeRule) == 0x000008, "Wrong alignment on WBP_Juno_WorldSettings_BaseSetting_C_SetContentSizeRule");
static_assert(sizeof(WBP_Juno_WorldSettings_BaseSetting_C_SetContentSizeRule) == 0x000048, "Wrong size on WBP_Juno_WorldSettings_BaseSetting_C_SetContentSizeRule");

// Function WBP_Juno_WorldSettings_BaseSetting.WBP_Juno_WorldSettings_BaseSetting_C.SetCustomIconVisibility
// 0x0018 (0x0018 - 0x0000)
struct WBP_Juno_WorldSettings_BaseSetting_C_SetCustomIconVisibility final
{
public:
	bool                                          IsCustom_0;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_BoolBool_ReturnValue;            // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2[0x6];                                        // 0x0002(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationReverse_ReturnValue;         // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationForward_ReturnValue;         // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Juno_WorldSettings_BaseSetting_C_SetCustomIconVisibility) == 0x000008, "Wrong alignment on WBP_Juno_WorldSettings_BaseSetting_C_SetCustomIconVisibility");
static_assert(sizeof(WBP_Juno_WorldSettings_BaseSetting_C_SetCustomIconVisibility) == 0x000018, "Wrong size on WBP_Juno_WorldSettings_BaseSetting_C_SetCustomIconVisibility");

// Function WBP_Juno_WorldSettings_BaseSetting.WBP_Juno_WorldSettings_BaseSetting_C.SetHoveredVisuals
// 0x0018 (0x0018 - 0x0000)
struct WBP_Juno_WorldSettings_BaseSetting_C_SetHoveredVisuals final
{
public:
	bool                                          IsHovered_0;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_BoolBool_ReturnValue;            // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2[0x6];                                        // 0x0002(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationReverse_ReturnValue;         // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationForward_ReturnValue;         // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Juno_WorldSettings_BaseSetting_C_SetHoveredVisuals) == 0x000008, "Wrong alignment on WBP_Juno_WorldSettings_BaseSetting_C_SetHoveredVisuals");
static_assert(sizeof(WBP_Juno_WorldSettings_BaseSetting_C_SetHoveredVisuals) == 0x000018, "Wrong size on WBP_Juno_WorldSettings_BaseSetting_C_SetHoveredVisuals");

// Function WBP_Juno_WorldSettings_BaseSetting.WBP_Juno_WorldSettings_BaseSetting_C.SetImportantVisuals
// 0x0058 (0x0058 - 0x0000)
struct WBP_Juno_WorldSettings_BaseSetting_C_SetImportantVisuals final
{
public:
	struct FSlateFontInfo                         K2Node_MakeStruct_SlateFontInfo;                   // 0x0000(0x0058)(HasGetValueTypeHash)
};
static_assert(alignof(WBP_Juno_WorldSettings_BaseSetting_C_SetImportantVisuals) == 0x000008, "Wrong alignment on WBP_Juno_WorldSettings_BaseSetting_C_SetImportantVisuals");
static_assert(sizeof(WBP_Juno_WorldSettings_BaseSetting_C_SetImportantVisuals) == 0x000058, "Wrong size on WBP_Juno_WorldSettings_BaseSetting_C_SetImportantVisuals");

// Function WBP_Juno_WorldSettings_BaseSetting.WBP_Juno_WorldSettings_BaseSetting_C.SetInitialDefaultValues
// 0x0020 (0x0020 - 0x0000)
struct WBP_Juno_WorldSettings_BaseSetting_C_SetInitialDefaultValues final
{
public:
	float                                         CallFunc_GetEndTime_ReturnValue;                   // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetEndTime_ReturnValue_1;                 // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_1;              // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Juno_WorldSettings_BaseSetting_C_SetInitialDefaultValues) == 0x000008, "Wrong alignment on WBP_Juno_WorldSettings_BaseSetting_C_SetInitialDefaultValues");
static_assert(sizeof(WBP_Juno_WorldSettings_BaseSetting_C_SetInitialDefaultValues) == 0x000020, "Wrong size on WBP_Juno_WorldSettings_BaseSetting_C_SetInitialDefaultValues");

// Function WBP_Juno_WorldSettings_BaseSetting.WBP_Juno_WorldSettings_BaseSetting_C.SetSettingName
// 0x0010 (0x0010 - 0x0000)
struct WBP_Juno_WorldSettings_BaseSetting_C_SetSettingName final
{
public:
	class FText                                   SettingName;                                       // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(WBP_Juno_WorldSettings_BaseSetting_C_SetSettingName) == 0x000008, "Wrong alignment on WBP_Juno_WorldSettings_BaseSetting_C_SetSettingName");
static_assert(sizeof(WBP_Juno_WorldSettings_BaseSetting_C_SetSettingName) == 0x000010, "Wrong size on WBP_Juno_WorldSettings_BaseSetting_C_SetSettingName");

}

